### ISSUE TITLE
ERROR: Unable to parse the inputStream Participant identifier value '' is invalid!

### ISSUE THREAD

**Issue by artur-kacen** [difi/oxalis#182]
Hi,

There is some problem with parsing response from APP_1000000014 (ibxplatform)

Looks like message is delivered successfully, but we cannot parse their response.
Currently we are using 3.0.1 version, maybe we should update to latest 3.0.2?
```
AS2 transmission faile
d : The following headers were received:
date: Mon, 06 Oct 2014 03:48:27 +0300
message-id: 4cc88371-6bc2-4eb9-83f0-0e655d396bbd
subject: AS2 message from OXALIS
content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1;           boundary="----=_Part_4332_1334204786.1412556507564"
as2-from: APP_1000000021
as2-to: APP_1000000014
disposition-notification-to: not.in.use@unit4.com
disposition-notification-options: signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
as2-version: 1.0
host: peppolap.ibxplatform.net
user-agent: Apache-HttpClient/4.3.5 (java 1.5)
accept-encoding: gzip,deflate
x-forwarded-proto: SSL
x-forwarded-for: 192.89.233.79
content-length: 661332

The message sent to AS2 System id APP_1000000021 on Mon, 06 Oct 2014 00:48:28 +0000 with subject AS2 MDN as you requested has been received.
It has been processed
The warning/error message is :
ERROR: Unable to parse the inputStream Participant identifier value '' is invalid!


java.lang.IllegalStateException: AS2 transmission failed : The following headers were received:
date: Mon, 06 Oct 2014 03:48:27 +0300
message-id: 4cc88371-6bc2-4eb9-83f0-0e655d396bbd
subject: AS2 message from OXALIS
content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1;           boundary="----=_Part_4332_1334204786.1412556507564"
as2-from: APP_1000000021
as2-to: APP_1000000014
disposition-notification-to: not.in.use@unit4.com
disposition-notification-options: signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
as2-version: 1.0
host: peppolap.ibxplatform.net
user-agent: Apache-HttpClient/4.3.5 (java 1.5)
accept-encoding: gzip,deflate
x-forwarded-proto: SSL
x-forwarded-for: 192.89.233.79
content-length: 661332
The message sent to AS2 System id APP_1000000021 on Mon, 06 Oct 2014 00:48:28 +0000 with subject AS2 MDN as you requested has been received.
It has been processed
The warning/error message is :
ERROR: Unable to parse the inputStream Participant identifier value '' is invalid!


        at eu.peppol.outbound.transmission.As2MessageSender.handleTheHttpResponse(As2MessageSender.java:231)
        at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:168)
        at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:83)
        at eu.peppol.outbound.transmission.Transmitter.transmit(Transmitter.java:48)
        at com.opuscapita.peppol.ap.transport.dest.PeppolDestination.store(PeppolDestination.java:89)
        at com.opuscapita.peppol.ap.transport.AsyncMessageProcessor.cloneStoreAndClose(AsyncMessageProcessor.java:207)
        at com.opuscapita.peppol.ap.transport.AsyncMessageProcessor.processValidMessage(AsyncMessageProcessor.java:196)
        at com.opuscapita.peppol.ap.transport.AsyncMessageProcessor.processMessage(AsyncMessageProcessor.java:134)
        at com.opuscapita.peppol.ap.transport.AsyncMessageProcessor.run(AsyncMessageProcessor.java:99)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)

```

**Comment by steinarcook** [comment]
Does this happen with every message or only with a certain message? Seems the error being returned indicates that there is a problem with actual contents, i.e. there is no Participant ID

**Comment by klakegg** [comment]
No response, please reopen if this is still a problem.
