### ISSUE TITLE
Oxalis AS2 implementation conflicting with other AS2 implementation

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#205]
It seems Oxalis As2 won't with other As2 implementation :

Stack trace:
	java.lang.IllegalStateException: Unable to retrieve the values from the MDN : Unsupported MDN content, expected InputStream found @ xx.xxxxx.xxxx.xxxx.DispositionDataSource@250b5e5b
	at eu.peppol.as2.MdnMimeMessageInspector.getMdnFields(MdnMimeMessageInspector.java:188)
	  at eu.peppol.as2.MdnMimeMessageInspector.isOkOrWarning(MdnMimeMessageInspector.java:200)
	  at eu.peppol.outbound.transmission.As2MessageSender.handleTheHttpResponse(As2MessageSender.java:220)
	  at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:162)
	  at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:77)
	  at eu.peppol.outbound.transmission.Transmitter.transmit(Transmitter.java:48)
	  at eu.peppol.outbound.transmission.Transmitter$transmit.call(Unknown Source)  
	Caused by: java.lang.Exception: Unsupported MDN content, expected InputStream found @ xx.xxxxx.xxxx.xxxx.DispositionDataSource@250b5e5b
	  at eu.peppol.as2.MdnMimeMessageInspector.getMdnFields(MdnMimeMessageInspector.java:183)
	  at eu.peppol.as2.MdnMimeMessageInspector.isOkOrWarning(MdnMimeMessageInspector.java:200)
	  at eu.peppol.outbound.transmission.As2MessageSender.handleTheHttpResponse(As2MessageSender.java:220)
	  at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:162)
	  at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:77)
	  at eu.peppol.outbound.transmission.Transmitter.transmit(Transmitter.java:48)
	  at eu.peppol.outbound.transmission.Transmitter$transmit.call(Unknown Source)

**Comment by teedjay** [comment]
Which version and AS2 implementation is this, do you have an endpoint / url we can debug against?

**Comment by aaron-kumar** [comment]
AS2 conflict is happening between oxalis-3.1.0 and our custom AS2 implementation used by legacy project. Unfortunately we can't remove legacy AS2 implementation.

**Comment by klakegg** [comment]
Does the custom AS2 implementation implement the OpenPEPPOL AS2 profile?

**Comment by aaron-kumar** [comment]
No. Custom AS2 implementation is not meant for Peppol or does not implement OpenPEPPOL AS2 profile. 

It is general purpose AS2 implementation meant to handle AS2 transport.

**Comment by milanaleksic** [comment]
Just a note that might help: it might be that the mapping present in our mailcap is coliding with standalone Oxalis's expectation that nobody should be handling that kind of messages:

    message/disposition-notification;;   x-java-content-handler=our_custom_dispositiondata_content

And because of this we get the stack trace mentioned above by @aaron-kumar

**Comment by aaron-kumar** [comment]
I found that this issue is closed without any fix. 

I am facing same issue (as2 conflict) when I re-run tests with master version.

**Comment by steinarcook** [comment]
Have you tried with the `release4` branch?
