### ISSUE TITLE
Error occurred while receiving the document from Peppol

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#211]
Hi,

We are getting an exception when we are receiving the document from Peppol. It is failed in our Inbound.  We are using our AS2. It was working fine previously, but after changed to AS2 it seems to be failed.

Please find the stack trace below, Kindly help us to resolve this issue.

 AS2 reception error: ERROR: null 
eu.peppol.as2.ErrorWithMdnException: ERROR: null
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:158) ~[oxalis-as2-3.0.2-SNAPSHOT.jar:na]
	at eu.peppol.inbound.server.AS2Servlet.doPost(AS2Servlet.java:166) ~[classes/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646) [servlet-api.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727) [servlet-api.jar:na]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.55]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.55]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171) [catalina.jar:7.0.55]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) [catalina.jar:7.0.55]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.55]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.55]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.55]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070) [tomcat-coyote.jar:7.0.55]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611) [tomcat-coyote.jar:7.0.55]
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314) [tomcat-coyote.jar:7.0.55]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-coyote.jar:7.0.55]
	at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
Caused by: java.lang.NullPointerException: null
	at com.vg.collabrr.oauth.OAuthService.getParameterMap(OAuthService.java:400) ~[CollabrrModule-3.0.2.jar:na]
	at com.vg.collabrr.oauth.OAuthService.accessResource(OAuthService.java:283) ~[CollabrrModule-3.0.2.jar:na]
	at com.vg.collabrr.inbound.OxalisCollabrrConnector.sendDocument(OxalisCollabrrConnector.java:97) ~[CollabrrModule-3.0.2.jar:na]
	at com.vg.collabrr.inbound.CollabrrMessageRepository.saveInboundMessage(CollabrrMessageRepository.java:59) ~[CollabrrModule-3.0.2.jar:na]
	at com.vg.collabrr.inbound.CollabrrMessageRepository.saveInboundMessage(CollabrrMessageRepository.java:99) ~[CollabrrModule-3.0.2.jar:na]
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:118) ~[oxalis-as2-3.0.2-SNAPSHOT.jar:na]
	... 26 common frames omitted
2015-05-11 05:00:33,670 WARN [eu.peppol.inbound.server.AS2Servlet] [] Returning negative MDN with explanatory message 
2015-05-11 05:00:33,710 ERROR [eu.peppol.inbound.server.AS2Servlet] [] Returned negative MDN : 
------=_Part_82_1893431356.1431320433674
Content-Type: multipart/report; report-type=disposition-notification; 
	boundary="----=_Part_80_620392026.1431320433670"

------=_Part_80_620392026.1431320433670
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

The following headers were received:
date: Mon, 11 May 2015 05:00:33 +0000
message-id: 7a9ef82d-e645-4c6d-81fd-c9e6c24b90f5
subject: AS2 message from OXALIS
content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1;	boundary="----=_Part_78_250212940.1431320433569"
as2-from: APP_1000000041
as2-to: AS2 System identifier, obtained from CN attribute of X.509 certificate
disposition-notification-to: not.in.use@unit4.com
disposition-notification-options: signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
as2-version: 1.0
host: peppolap.everbinding.nl
connection: Keep-Alive
user-agent: Apache-HttpClient/4.3.5 (java 1.5)
accept-encoding: gzip,deflate
content-length: 24905

The message sent to AS2 System id APP_1000000041 on Mon, 11 May 2015 05:00:33 +0000 with subject AS2 MDN as you requested has been received.
It has been processed 
The warning/error message is :
ERROR: null

Thanks,
Vijay

**Comment by teedjay** [comment]
1 - Seems like it stops after message has been received and during the "saveInboundMessage" phase.  Have you compiled your "CollabrrMessageRepository" against the correct / same Oxalis version?

2 - You also seem to use Oxalis 3.0.2, which has some known SSL security issues, you should use a newer version.

Who is the sender and what kind of PEPPOL document do you try to receive?

**Comment by steinarcook** [comment]
No answer to Thore's questions, so this is probably not a problem any longer.
