### ISSUE TITLE
mvn clean install failing while test module....

### ISSUE THREAD

**Issue by ahmedinweb** [difi/oxalis#222]
Hi,
We are yet to get certs from PEPPOL, before that I want to build from src and test.
While building its failing in test.

Basic question: do we need to have certs from PEPPOL even for build/test??

Your early response is highly appreciable. Thanks.

This exception is from report.
eu.peppol.security.OcspValidatorCacheTest#test01

Exception
java.lang.AssertionError: expected [true] but found [false]
	at eu.peppol.security.OcspValidatorCacheTest.test01(OcspValidatorCacheTest.java:31)
... Removed 39 stack frames

The exception from command line.....

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Oxalis - PEPPOL access point Plug-and-Play ........ SUCCESS [1.520s]
[INFO] Oxalis-api ........................................ SUCCESS [31.649s]
[INFO] Oxalis commons .................................... FAILURE [38.554s]
[INFO] oxalis-jdbc-dbcp .................................. SKIPPED
[INFO] oxalis-sql ........................................ SKIPPED
[INFO] oxalis-as2 ........................................ SKIPPED
[INFO] Oxalis START inbound (WAR) ........................ SKIPPED
[INFO] Oxalis outbound ................................... SKIPPED
[INFO] Oxalis standalone CLI program ..................... SKIPPED
[INFO] oxalis-distribution ............................... SKIPPED
[INFO] oxalis-integration-test ........................... SKIPPED
[INFO] oxalis-jdbc-jndi .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:12.050s
[INFO] Finished at: Mon Aug 24 13:58:21 EDT 2015
[INFO] Final Memory: 32M/155M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
14.1:test (default-test) on project oxalis-commons: There are test failures.
[ERROR]
[ERROR] Please refer to C:\oxalis-master\3.1\oxalis-commons\target\surefire-repo
rts for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal o
rg.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on proj
ect oxalis-commons: There are test failures.

Please refer to C:\oxalis-master\3.1\oxalis-commons\target\surefire-reports for
the individual test results.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBu
ild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures
.

Please refer to C:\oxalis-master\3.1\oxalis-commons\target\surefire-reports for
the individual test results.
        at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(Suref
ireHelper.java:82)
        at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(Surefir
ePlugin.java:169)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPre
conditionsChecked(AbstractSurefireMojo.java:733)
        at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(Abstrac
tSurefireMojo.java:631)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :oxalis-commons
C:\oxalis-master\3.1>

![image](https://cloud.githubusercontent.com/assets/13949185/9448081/931c2762-4a68-11e5-826b-1a982317e4da.png)

**Comment by teedjay** [comment]
If you just want to compile and build the code you could skip the tests :  

    mvn clean install -Dmaven.test.skip=true

**Comment by ahmedinweb** [comment]
I did skip the tests for building, to proceed further. Thanks...
I am wondering, are there any sample certs or test env to test integration?

Installation guide says 443 port should be used tomcat ssl, Can't we configure this to diff port? 

We are going to user oracle db and I changed connection info (driver,url, etc.) in global.properties file.

I guess the below keys need certs to test? rest all self explanatory.
oxalis.keystore=C:/oxalis-master/oxalis-keystore.jks
oxalis.sml.hostname=smk.peppolcentral.org

Thanks for your time teedjay..

**Comment by klakegg** [comment]
There are no sample cert available to everyone to use.

Installations of Oxalis made available to the OpenPEPPOL network are strongly recommanded to standardized HTTPS port (443) for transportation as that ensures a smooth inclusion in the network.
