### ISSUE TITLE
TransmissionRequestBuilderTest fails with TestNG > 6.8.7

### ISSUE THREAD

**Issue by steinarcook** [difi/oxalis#234]
Upgrading TestNG to any release after 6.8.7 cause ```TransmissionRequestBuilderTest```to fail:

```java
com.google.inject.ConfigurationException: Guice configuration errors:

1) Unable to create binding for eu.peppol.smp.SmpLookupManager. It was already configured on one or more child injectors or private modules
    bound at eu.peppol.outbound.transmission.TransmissionTestModule.getSmpLookupManager()
  If it was in a PrivateModule, did you forget to expose the binding?
  while locating eu.peppol.smp.SmpLookupManager
    for parameter 2 at eu.peppol.outbound.transmission.TransmissionRequestBuilder.<init>(TransmissionRequestBuilder.java:68)
  while locating eu.peppol.outbound.transmission.TransmissionRequestBuilder

1 error
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:961)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at eu.peppol.outbound.transmission.OverridableTransmissionRequestBuilderCreator.createTansmissionRequestBuilderAllowingOverrides(OverridableTransmissionRequestBuilderCreator.java:22)
	at eu.peppol.outbound.transmission.TransmissionRequestBuilderTest.setUp(TransmissionRequestBuilderTest.java:54)

```

**Comment by steinarcook** [comment]
Fixed by removing OverridableTransmissionRequestBuilderCreator.java
