### ISSUE TITLE
test fails during compilation when trying to access http://smp.difi.no/iso6523-actorid-upis%3A%3A9908%3A9854323

### ISSUE THREAD

**Issue by hmspider** [difi/oxalis#249]
the resource in cause is not accessible via http (404), ok with https though.

Found at least one occurrence in the code (line 40 in SmpContentRetrieverImplTest.java):

    new SmpContentRetrieverImpl().getUrlContent(new URL("http://smp.difi.no/iso6523-actorid-upis%3A%3A9908%3A9854323/"));

This is the class referred to in the error msg (courtesy Filipe Ildefonso):

> 2016-05-05 11:43:44,936 DEBUG [eu.peppol.security.PeppolKeystoreLoader] Loading and combining trust stores: truststore-test.jks
2016-05-05 11:43:44,937 DEBUG [eu.peppol.security.KeyStoreUtil] Loading trust store from truststore-test.jks
2016-05-05 11:43:44,945 DEBUG [eu.peppol.security.KeyStoreUtil] Adding alias peppol-root-0 for certificate CN=PEPPOL Root TEST CA, OU=FOR TEST PURPOSES ONLY, O=NATIONAL IT AND TELECOM AGENCY, C=DK
2016-05-05 11:43:44,946 DEBUG [eu.peppol.security.KeyStoreUtil] Adding alias peppol-smp-0 for certificate CN=PEPPOL SERVICE METADATA PUBLISHER TEST CA, OU=FOR TEST PURPOSES ONLY, O=NATIONAL IT AND TELECOM AGENCY, C=DK
2016-05-05 11:43:44,946 DEBUG [eu.peppol.security.KeyStoreUtil] Adding alias peppol-ap-0 for certificate CN=PEPPOL ACCESS POINT TEST CA, OU=FOR TEST PURPOSES ONLY, O=NATIONAL IT AND TELECOM AGENCY, C=DK
2016-05-05 11:43:44,946 DEBUG [eu.peppol.security.KeyStoreUtil] Adding alias peppol-sts-0 for certificate CN=PEPPOL SECURITY TOKEN SERVICE TEST CA, OU=FOR TEST PURPOSES ONLY, O=NATIONAL IT AND TELECOM AGENCY, C=DK
2016-05-05 11:43:44,947 DEBUG [eu.peppol.security.PeppolKeystoreLoader] Loading PEPPOL keystore from /tmp/unit-test933274710902108046/oxalis-keystore.jks
2016-05-05 11:43:44,947 DEBUG [eu.peppol.security.KeyStoreUtil] Attempting to open /tmp/unit-test933274710902108046/oxalis-keystore.jks
Tests run: 53, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 146.583 sec <<< FAILURE! - in TestSuite
test404(eu.peppol.smp.SmpContentRetrieverImplTest)  Time elapsed: 127.487 sec  <<< FAILURE!
java.lang.IllegalStateException: Unable to connect to http://smp.difi.no/iso6523-actorid-upis%3A%3A9908%3A9854323/ ; Connection timed out
        at eu.peppol.smp.SmpContentRetrieverImplTest.test404(SmpContentRetrieverImplTest.java:38)
Caused by: java.net.ConnectException: Connection timed out
        at eu.peppol.smp.SmpContentRetrieverImplTest.test404(SmpContentRetrieverImplTest.java:38)

>Results :

>Failed tests:
  SmpContentRetrieverImplTest.test404:38 » IllegalState Unable to connect to htt...

**Comment by steinarcook** [comment]
The purpose of this test is to verify that the given URL returns 404. In this case the connection has timed out for some reson unknown to me. Running the tests or pasting the URL into the browser gives the expected result, i.e. 404.

I guess smp.difi.no was temporarily unavailable.

**Comment by steinarcook** [comment]
I have also annotated the test as "integration" in order to ensure that it is not executed during ordinary build.
