### ISSUE TITLE
Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class eu.peppol.util.GlobalConfiguration

### ISSUE THREAD

**Issue by odha** [difi/oxalis#274]
Hi,
I'm currently writing a Java servicetype for Sonic ESB, using 
< dependency>
   < groupId>no.difi.oxalis< /groupId>
   < artifactId>oxalis-outbound< /artifactId>
   <version>3.2.0< /version>
< /dependency>

When running my code, I get the following error:

com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class eu.peppol.util.GlobalConfiguration

Im not sure what the problem is? Maybe you can help me out? The class is part of the POM-dependency, so theoretically it should always be found?

Regards,

Onno

------------------- full stack trace  -------------------

com.google.inject.ProvisionException: Guice provision errors:

1) Error injecting constructor, java.lang.NoClassDefFoundError: Could not initialize class eu.peppol.util.GlobalConfiguration
  at eu.peppol.smp.SmpLookupManagerImpl.<init>(SmpLookupManagerImpl.java:91)
  while locating eu.peppol.smp.SmpLookupManagerImpl
  while locating eu.peppol.smp.SmpLookupManager
    for parameter 2 at eu.peppol.outbound.transmission.TransmissionRequestBuilder.<init>(TransmissionRequestBuilder.java:68)
  while locating eu.peppol.outbound.transmission.TransmissionRequestBuilder

1 error
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at eu.peppol.outbound.OxalisOutboundModule.getTransmissionRequestBuilder(OxalisOutboundModule.java:36)
	at nl.vanmeijel.sonic.servicetypes.OxalisClient.OxalisClient.doService(OxalisClient.java:62)
	at com.sonicsw.esb.service.common.impl.AbstractSFCServiceImpl.service(AbstractSFCServiceImpl.java:267)
	at com.sonicsw.xqimpl.service.debug.DebugServiceInterceptor.intercept(DebugServiceInterceptor.java:118)
	at com.sonicsw.xqimpl.service.XQServiceChain$XQInterceptorServiceWrapper.intercept(XQServiceChain.java:495)
	at com.sonicsw.xqimpl.service.XQServiceChain$XQInterceptorServiceWrapper.service(XQServiceChain.java:484)
	at com.sonicsw.xqimpl.service.XQServiceChain.service(XQServiceChain.java:152)
	at com.sonicsw.xqimpl.service.ServiceMessageHandler.callService(ServiceMessageHandler.java:424)
	at com.sonicsw.xqimpl.service.ServiceMessageHandler.handleMessageCommon(ServiceMessageHandler.java:236)
	at com.sonicsw.xqimpl.service.ServiceMessageHandler.handleMessage(ServiceMessageHandler.java:99)
	at com.sonicsw.xqimpl.service.XQDispatcher.onMessage(XQDispatcher.java:436)
	at com.sonicsw.xqimpl.endpoint.container.EndpointContextContainer.onMessage(EndpointContextContainer.java:114)
	at com.sonicsw.xq.connector.jms.JMSEndpointMessageListener.onMessage(JMSEndpointMessageListener.java:243)
	at progress.message.jimpl.Session.deliver(Session.java:3078)
	at progress.message.jimpl.Session.run(Session.java:2481)
	at progress.message.jimpl.Session$SessionThread.run(Session.java:2873)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class eu.peppol.util.GlobalConfiguration
	at eu.peppol.smp.SmpLookupManagerImpl.discoverSmlHost(SmpLookupManagerImpl.java:113)
	at eu.peppol.smp.SmpLookupManagerImpl.<init>(SmpLookupManagerImpl.java:91)
	at eu.peppol.smp.SmpLookupManagerImpl$$FastClassByGuice$$cd2e6a73.newInstance(<generated>)
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	... 17 more

**Comment by klakegg** [comment]
NoClassDefFoundError is an error triggered by your environment and must be debugged there.

**Comment by odha** [comment]
Hi,
I just found out today, that the class is presenet in my Java classpath, but can't be instantiated. Subsequent requests give a NoClassDefFound error, but that is not because the class is missing, but because Guice was unable to load it.
The reason was indeed an configuration error, just like you mentioned.

Thanks!
