### ISSUE TITLE
end point url Disposition header set exception occurred during outbound

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#279]
Hi All,

We are using the following oxalis version,

version.oxalis: 3.0.2-SNAPSHOT
version.java: 1.7.0_51
oxalis.operation.mode: PRODUCTION
oxalis.pki.version: V2
oxalis.sml.hostname: edelivery.tech.ec.europa.eu
certificate.subject: O=eConnect International B.V.,CN=APP_1000000187,C=NL
certificate.issuer: CN=PEPPOL ACCESS POINT CA,O=NATIONAL IT AND TELECOM AGENCY,C=DK
certificate.expired: false

We are able to exchange the document via our access point to many providers even now also. But we are facing an issue w.r.t the specific company (which was newly added) when we are doing outbound. 

Here is the exception we are getting,

### end point url
Disposition header set:signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
Exception while sending invoice :java.lang.IllegalStateException: Unable to retrieve the plain text from the MDN: null
	at eu.peppol.as2.MdnMimeMessageInspector.getPlainTextPartAsText(MdnMimeMessageInspector.java:132)
	at eu.peppol.outbound.transmission.As2MessageSender.handleTheHttpResponse(As2MessageSender.java:229)
	at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:172)
	at eu.peppol.outbound.transmission.As2MessageSender.send(As2MessageSender.java:83)
	at eu.peppol.outbound.transmission.Transmitter.transmit(Transmitter.java:48)
	at com.vg.collabrr.outbound.handlers.DocumentHandler.sendDocument(DocumentHandler.java:148)
	at com.vg.collabrr.outbound.handlers.DocumentHandler.handleRequest(DocumentHandler.java:46)
	at com.vg.collabrr.outbound.CollabrrPeppolServlet.doPost(CollabrrPeppolServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
	at eu.peppol.as2.MdnMimeMessageInspector.getPlainTextPartAsText(MdnMimeMessageInspector.java:130)
	... 29 more

Could any one help us, how can we solve this issue and proceed further ?

Thanks,
Vijay

**Comment by klakegg** [comment]
This does not look like a bug in Oxalis.
