### ISSUE TITLE
Oxalis webapp not starting, with error

### ISSUE THREAD

**Issue by pschoond** [difi/oxalis#297]
Hello,

When I start Tomcat with the oxalis webapp, oxalis doesn't start. I find the following error in the log:
09-Aug-2017 00:13:26.675 SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [guiceFilter]
 com.google.inject.ProvisionException: Unable to provision, see the following errors:
=================
1) Error in custom provider, com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: sun.security.provider.certpath.OCSP.check(Ljava/security/cert/X509Certif
icate;Ljava/security/cert/X509Certificate;)Lsun/security/provider/certpath/OCSP$RevocationStatus;
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:53)
  while locating no.difi.vefa.peppol.mode.Mode
    for the 3rd parameter of no.difi.oxalis.inbound.servlet.StatusServlet.<init>(StatusServlet.java:58)
  at no.difi.oxalis.inbound.servlet.StatusServlet.class(StatusServlet.java:58)
  while locating no.difi.oxalis.inbound.servlet.StatusServlet
==================
I followed the installation.md and keystore.md guides. Here are some details:
OS: CentOS 6.9
Java: openjdk version "1.8.0_141"
Tomcat: 9.0.0.M22
oxalis distribution: 4.0.0RC2
 
Tomcat is running fine behind Apache port 443
There is a testcert from Peppol in the Keystore.

I had to set a password on the entry in the keystore for Oxalis to be able to read it (got a different error earlier about not being able to read the key), although the documentation says there should not be. Could this introduce the problem with the filter ?
Or is there some other configuration parameter ? 

This is my oxalis.conf file:
===========
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=oxalis-keystore.jks
     password=peppol
     key.alias=test
     key.password=peppol
 }
 
 \# The relative name of the directory holding plugin
\# oxalis.path.plugin = oxalis-plugin
oxalis.path.plugin = ../oxalis
 
 \# Signals to Oxalis that we should look for plugin
 oxalis.persister.receipt = plugin
 
 \# Where to store inbound files
 oxalis.path.inbound = /data/peppol/IN

 \# logfile
oxalis.logging.config = logback-oxalis.xml

 
\# Mode of operation? Specify TEST for pilot/test certificate or PRODUCTION for production (defaults to TEST)
oxalis.operation.mode=TEST
===============

I'm not sure what to do with the oxalis.path.plug parameter. Where should it point to ?

Hope someone can help with this.

Regards,

Paul

**Comment by pschoond** [comment]
Sorry, screwd up the layout, can't seem to get it right again.

**Comment by pabrah** [comment]
I get the same error on Ubuntu 16.04 LTS with javac 1.8.0_131 and tomcat 9.0.0.M18 (our production server).
This error occured on a server where oxalis was running fine under tomcat, but after a restart of tomcat (shutdown and startup scripts) it suddenly could not start oxalis anymore, without any updates or changes made by us.
Hope this gets resolved soon since it's stopping our clients from receiving their invoices.

Regards
Petter Abrahamsen

**Comment by pschoond** [comment]
@pabrah 
If nothing changed on the server then maybe it pulls something from the Internet during startup, which has changed. Google guice ? (no idea how this works)

Regards,
Paul

**Comment by pschoond** [comment]
Just compiled 4.0.0.RC3. Couldn't find anything usefull in oxalis-distribution but found a war file in oxalis-inbound/target. Deployed it but same error.

**Comment by pschoond** [comment]
It appears that the error is caused because of a missing library file in the oxalis.war file. It can be solved in the running Tomcat server by downloading the oxalis-server from: https://search.maven.org/remotecontent?filepath=no/difi/oxalis/oxalis-server/4.0.0-RC2/oxalis-server-4.0.0-RC2-full.tar.gz, unpacking it and copy the file oxalis-outbound-4.0.0-RC2.jar from the lib directory to $TOMCAT_HOME/oxalis/webapp/WEB-INF/lib.
Not there yet because now we get the next error:
=============
SEVERE [main] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [no.difi.oxalis.inbound.OxalisGuiceContextListener]
 java.lang.NoClassDefFoundError: org/apache/http/conn/HttpClientConnectionManager
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.loadModule(GuiceModuleLoader.java:116)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.load(GuiceModuleLoader.java:111)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.getModules(GuiceModuleLoader.java:98)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:64)
        at no.difi.oxalis.inbound.OxalisGuiceContextListener.<init>(OxalisGuiceContextListener.java:42)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:120)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4555)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5095)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:740)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:716)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:703)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1850)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:762)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:431)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1578)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:308)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:964)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:839)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1425)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1415)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:941)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:258)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:422)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:770)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:657)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:355)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:495)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.HttpClientConnectionManager
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1269)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1104)
=====================

**Comment by pabrah** [comment]
# Solution:
Download Java 1.8.0_45 tar gz file and install it (you can download it from oracles archive, just create a user).
Download from here: http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html 
Download the 1.8.0_45.tar.gz file (might not be able to do this from command line, since you have to be logged in). 
Move the tar.gz file to /usr/lib/jvm
Unpack the tar.gz file in /usr/lib/jvm (sudo tar xvzf jdk1.8.0_45....tar.gz)
### Run these two commands to set the java and javac paths:
sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.8.0_45/jre/bin/java 1800
sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.8.0_45/bin/javac 1800

### To change versions (for upgrades or otherwise), you can run these:
sudo update-alternatives --config java
sudo update-alternatives --config javac

Export the java home directory
export JAVA_HOME=/usr/lib/jvm/jdk1.8.0_45

Restart Tomcat and this should fix this issue.

**Comment by pschoond** [comment]
@pabrah Thanks for your comment, but unfortunately no difference. Same error. More info:
From what it looks like to me, the GuiceModuleLoader loads several modules but stops at or after ApacheHttpModule. From catalina.out log:
=================
16-Aug-2017 16:45:02.325 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/apache-tomcat-9.0.0.M22/webapps/oxalis.war]
16-Aug-2017 16:45:03.264 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
16:45:03.351 [main] DEBUG no.difi.oxalis.commons.guice.GuiceModuleLoader - Loading module 'no.difi.oxalis.commons.timestamp.TimestampModule'.
16:45:03.354 [main] DEBUG no.difi.oxalis.commons.guice.GuiceModuleLoader - Loading module 'no.difi.oxalis.commons.evidence.EvidenceModule'.
16:45:03.354 [main] DEBUG no.difi.oxalis.commons.guice.GuiceModuleLoader - Loading module 'no.difi.oxalis.commons.http.ApacheHttpModule'.
16-Aug-2017 16:45:03.355 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
==================
Not sure if the TLD info message is important.
(sorry for the layout, don't understand this styling with Markdown)

Regards,

Paul

**Comment by pschoond** [comment]
Looking at version 3 install guide it seems that Metro is needed because Oxalis makes heavy use of it. In version 4 there is no mention anymore for Metro. Is this not needed anymore ?

Regards,

Paul

**Comment by steinarcook** [comment]
No, Metro is no longer needed, as we no longer use the SOAP based protocol named "START".

Steinar Overbeck Cook
+47 90665793

**Comment by pschoond** [comment]
Hello,

@klakegg Is this problem fixed by this commit f2de90d ?

**Comment by pschoond** [comment]
Managed to compile the source from oxalis-4.0.0.RC3 with:
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdist

 Moved the oxalis.war file to the webapp directory of Tomcat and now everything seems fine. So the distribution files from the Mavis repository are not up2date or this was solved in RC3.

Regards,
Paul

**Comment by jannewaren** [comment]
Hello!

So this is fixed in master but not in any releases? Is there any plan to release a 4.0.0-RC3 or something into the Maven repo, because currently setting up an Access Point with 4.0.0-RC2 seems impossible?

Could you release a new version where this is fixed? 😄

**Comment by ajaysodhi** [comment]
I recently setup Oxalis 4.0.2 Release on Tomcat 9.  I was facing lots of errors as you guys are facing. Found solution, hope will help you as well who are still struggling for the setup.

**Prerequisites:**
1.  Java 8 (Any version)
2.  Tomcat 9

**Steps to run the oxalis build:**

1.  Download the latest 4.0.2 release from https://github.com/difi/oxalis/releases/tag/oxalis-4.0.2
2.  Build the war using command: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pdist
3.  go to target at location: oxalis-oxalis-4.0.2\target\distribution\jee\oxalis.war
4.  Deploy that war in tomcat 9.
5.  It will show you errors like mentioned above (apache is stopped already)
6.  Copy **guava-26.0-jre.jar** and **guava-r438.jar** in tomcat 9/lib folder.
7.  Clear tomcat9/work/* folder
8.  Restart tomcat. Oxalis will be up and running.
