### ISSUE TITLE
Problem oxalis-standalone - Test Send Example Invoice

### ISSUE THREAD

**Issue by itEnercomSwiss** [difi/oxalis#337]
Hi everybody.
When launch the following command:

java -jar /opt/target/oxalis-standalone.jar -f /opt/target/BII04_T10_PEPPOL-v2.0_invoice.xml -u https://xxx.com/oxalis/as2 -r 9908:810418052 -s 9927:278212084 -cert /opt/oxalis/.oxalis/cert.cer

We have the following result:

_2018-07-31 15:33:19,718 WARN [no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder] Endpoint was set by caller not retrieved from SMP, make sure this is intended behaviour. 
2018-07-31 15:33:20,404 ERROR [no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 500 from https://xxx.com/oxalis/as2 
2018-07-31 15:33:20,409 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!! 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:216)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleFailedRequest(As2MessageSender.java:360)
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:259)
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:231)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:144)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:130)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:82)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:165)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:93)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1_

What is the problem?
I hope for your cooperation.
Thanks

**Comment by itEnercomSwiss** [comment]
Cert.cer is the test certificate from PEPPOL.

**Comment by klakegg** [comment]
Please clarify what is the reported bug.

**Comment by itEnercomSwiss** [comment]
The reported bug refers to the following test: "Sending a sample invoice to your own local access point".

**Comment by klakegg** [comment]
Closed as the error triggered in Oxalis inbound is not shared.

**Comment by S3HS** [comment]
I have the exactly same error. Probably out of scope for Oxalis, but did you find the solution for this? @itEnercomSwiss

**Comment by adarshsrivastava11** [comment]
I'm facing the same issue, is there any solution to this?
