### ISSUE TITLE
With Oxalis 4.0.2 Version, When deploying the application getting the following exception

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#348]
We are getting the following exception after deploying the Oxalis 4.0.2 version in the tomcat.

07-Sep-2018 09:17:45.919 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
07-Sep-2018 09:17:45.923 SEVERE [main] org.apache.catalina.core.StandardContext.startInternal Context [/oxalis] startup failed due to previous errors
07-Sep-2018 09:17:45.934 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/oxalis/oxalis-server/webapps/oxalis.war] has finished in [2,252] ms
07-Sep-2018 09:17:45.934 INFO [main] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/opt/oxalis/oxalis-server/webapps/ROOT]
07-Sep-2018 09:17:45.939 INFO [AsyncFileHandlerWriter-424058530] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [no/difi/oxalis/commons/logging/LoggingHandler.class]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [no/difi/oxalis/commons/logging/LoggingHandler.class]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1329)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResourceAsStream(WebappClassLoaderBase.java:1065)
	at java.lang.Class.getResourceAsStream(Class.java:2223)
	at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:61)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
	at com.google.inject.internal.Messages.formatSource(Messages.java:241)
	at com.google.inject.internal.Messages.formatSource(Messages.java:220)
	at com.google.inject.internal.Messages.formatInjectionPoint(Messages.java:276)
	at com.google.inject.internal.Messages.formatSource(Messages.java:235)
	at com.google.inject.internal.Messages.formatSource(Messages.java:220)
	at com.google.inject.internal.Messages.formatMessages(Messages.java:90)
	at com.google.inject.CreationException.getMessage(CreationException.java:50)
	at java.lang.Throwable.getLocalizedMessage(Throwable.java:391)
	at java.lang.Throwable.toString(Throwable.java:480)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintWriter.println(PrintWriter.java:754)
	at java.lang.Throwable$WrappedPrintWriter.println(Throwable.java:764)
	at java.lang.Throwable.printStackTrace(Throwable.java:655)
	at java.lang.Throwable.printStackTrace(Throwable.java:721)
	at org.apache.juli.OneLineFormatter.format(OneLineFormatter.java:147)
	at org.apache.juli.FileHandler.publish(FileHandler.java:282)
	at org.apache.juli.AsyncFileHandler.publishInternal(AsyncFileHandler.java:146)
	at org.apache.juli.AsyncFileHandler$LogEntry.flush(AsyncFileHandler.java:185)
	at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:161)

Could any one faced the same kind of issue previously.

**Comment by jangj** [comment]
didi you get it to work?
have you tried this: #318

**Comment by VijayaKumar2** [comment]
Yeah... I have deployed the war and build our customization module separately and deploy it as a jar. Basically the dependency of guava-26.0-jre.jar causing this problem. Oxalis need guava-26.0-jre.jar only, if we are having any customization then we need to update to the latest version
