### ISSUE TITLE
Getting the following exception from SMP  

### ISSUE THREAD

**Issue by VijayaKumar2** [difi/oxalis#351]
Hi,

When we are sending the document from Oxalis, getting the following exception.

Caused by: java.util.concurrent.ExecutionException: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:492)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:196)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2312)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at no.difi.oxalis.outbound.lookup.CachedLookupService.lookup(CachedLookupService.java:70)
	... 32 more
Caused by: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
	at no.difi.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:56)
	at no.difi.vefa.peppol.lookup.LookupClient.getServiceMetadata(LookupClient.java:100)
	at no.difi.vefa.peppol.lookup.LookupClient.getEndpoint(LookupClient.java:119)
	at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:78)
	at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	... 38 more
Caused by: no.difi.certvalidator.api.FailedValidationException: Validation of subject principal(CN) failed.
	at no.difi.certvalidator.rule.PrincipalNameRule.validate(PrincipalNameRule.java:64)
	at no.difi.certvalidator.structure.AndJunction.validate(AndJunction.java:23)
	at no.difi.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:35)
	at no.difi.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:12)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
	at no.difi.certvalidator.util.CachedValidatorRule.validate(CachedValidatorRule.java:29)
	at no.difi.certvalidator.ValidatorGroup.validate(ValidatorGroup.java:46)
	at no.difi.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:54)
	... 44 more

**Comment by kukel** [comment]
Or when you have a 'test' SMP that signes its responses with a 'prod' certificate. Oxalis is very bad in the explicitly of responses... Lots of things expect 'happy days' scenario's. In my case a 'SMP response not signed with a correct certificate' instead of a generic "Validation of subject principal(CN) failed."
