### ISSUE TITLE
Error while sending document in test mode using standalone

### ISSUE THREAD

**Issue by paulm76** [difi/oxalis#362]
Hello,

I tried to send an invoice using the standalone. The command I used was `java -jar oxalis-standalone.jar -f invoice_difi.xml -r 9908:810418052 -s 9956:0630675588`. I am using the 4.0.2-SNAPSHOT version of oxalis.

Here is the stack trace : 
```
2018-10-05 12:00:00,317 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder:/home/ec2-user
2018-10-05 12:00:00,321 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /home/ec2-user/conf
2018-10-05 12:00:00,323 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /home/ec2-user/conf/oxalis.conf
2018-10-05 12:00:00,333 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Timestamp
2018-10-05 12:00:00,335 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: system
2018-10-05 12:00:00,335 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Evidence
2018-10-05 12:00:00,335 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: rem
2018-10-05 12:00:00,335 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: HTTP
2018-10-05 12:00:00,336 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_TOTAL: 20
2018-10-05 12:00:00,336 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_MAX_ROUTE: 2
2018-10-05 12:00:00,336 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_CONNECT: 0
2018-10-05 12:00:00,337 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_READ: 0
2018-10-05 12:00:00,337 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Error
2018-10-05 12:00:00,337 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TRACKER: quiet
2018-10-05 12:00:00,337 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: AS2
2018-10-05 12:00:00,337 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HOSTNAME:
2018-10-05 12:00:00,338 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => NOTIFICATION: not.in.use@difi.no
2018-10-05 12:00:00,338 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => MSGID_GENERATOR: default
2018-10-05 12:00:00,338 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: File system
2018-10-05 12:00:00,338 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => CONF: /mtn/.oxalis/conf
2018-10-05 12:00:00,338 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => INBOUND: /mnt/peppol/IN
2018-10-05 12:00:00,338 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PLUGIN: plugin
2018-10-05 12:00:00,339 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Key store
2018-10-05 12:00:00,339 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PATH: oxalis-keystore.jks
2018-10-05 12:00:00,339 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PASSWORD: *****
2018-10-05 12:00:00,340 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_ALIAS: *****
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_PASSWORD: *****
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Header
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PARSER: sbdh
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Persister
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PAYLOAD: default
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => RECEIPT: default
2018-10-05 12:00:00,341 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HANDLER: default
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tracing
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => REPORTER: noop
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HTTP: null
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transformer
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => DETECTOR: legacy
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => WRAPPER: xml
2018-10-05 12:00:00,342 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Statistics
2018-10-05 12:00:00,343 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: noop
2018-10-05 12:00:00,343 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transmission
2018-10-05 12:00:00,344 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => VERIFIER: default
2018-10-05 12:00:00,345 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Logging
2018-10-05 12:00:00,345 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => CONFIG: null
2018-10-05 12:00:00,347 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: logback
2018-10-05 12:00:00,348 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tag
2018-10-05 12:00:00,348 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => GENERATOR: noop
2018-10-05 12:00:00,361 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
2018-10-05 12:00:00,362 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
2018-10-05 12:00:00,362 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0
2018-10-05 12:00:01,753 INFO [no.difi.oxalis.commons.mode.ModeModule] Detected mode: TEST


2018-10-05 12:00:02,413 INFO [eu.sendregning.oxalis.Main] Using 10 threads

Message failed : null

2018-10-05 12:00:02,648 ERROR [no.difi.oxalis.commons.error.QuietErrorTracker] [bcf0385d-220a-47c1-8887-1672b2c0bfc3] null
java.lang.NullPointerException: null
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:122)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:91)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-10-05 12:00:02,654 ERROR [eu.sendregning.oxalis.Main] Execution failed: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:221)
Caused by: java.lang.NullPointerException: null
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:122)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:91)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1
```

After adding loggers, it seems that the `transmissionMessage` is null in the DefaultTransmitter class line 109.

Do I miss something in the command or is there something to configure I forgot ?

**Comment by cook32** [comment]
Did you correctly set your environment variables ?

JAVA_HOME
CATALINA_BASE
CATALINA_HOME
OXALIS_HOME

**Comment by paulm76** [comment]
```
JAVA_HOME="/usr/lib/jvm/jre"
CATALINA_BASE="/usr/share/tomcat8"
CATALINA_HOME="/usr/share/tomcat8"
OXALIS_HOME="/mnt/.oxalis"
```

I think values are well set...
I tried to move my standalone jar in different folders but I always have the same error.
