### ISSUE TITLE
Validation of subject principal(CN) failed.

### ISSUE THREAD

**Issue by robrechtD** [difi/oxalis#369]
When sending a document through oxalis we receive the following Exception: 

2018-10-04 11:13:08,085 ERROR [eu.sendregning.oxalis.OutboundServer] [] Sending document failed: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed. no.difi.oxalis.api.lang.OxalisTransmissionException: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
	at no.difi.oxalis.outbound.lookup.CachedLookupService.lookup(CachedLookupService.java:68)
	at no.difi.oxalis.api.lookup.LookupService.lookup(LookupService.java:57)
	at no.difi.oxalis.outbound.transmission.TransmissionRequestBuilder.build(TransmissionRequestBuilder.java:189)
	at eu.sendregning.oxalis.OutboundServer.send(OutboundServer.java:335)
	at eu.sendregning.oxalis.OutboundServer.send(OutboundServer.java:304)
	at eu.sendregning.oxalis.OutboundServer.processCustomer(OutboundServer.java:212)
	at eu.sendregning.oxalis.OutboundServer.detectAndProcessCustomers(OutboundServer.java:123)
	at eu.sendregning.oxalis.OutboundServer.run(OutboundServer.java:86)
	at eu.sendregning.oxalis.Main.main(Main.java:47)
Caused by: java.util.concurrent.ExecutionException: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at com.google.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:143)
	at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2352)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2324)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at no.difi.oxalis.outbound.lookup.CachedLookupService.lookup(CachedLookupService.java:66)
	... 8 more
Caused by: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
	at no.difi.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:58)
	at no.difi.vefa.peppol.lookup.LookupClient.getServiceMetadata(LookupClient.java:72)
	at no.difi.vefa.peppol.lookup.LookupClient.getEndpoint(LookupClient.java:91)
	at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:74)
	at no.difi.oxalis.outbound.lookup.CachedLookupService.load(CachedLookupService.java:43)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	... 14 more
Caused by: no.difi.certvalidator.api.FailedValidationException: Validation of subject principal(CN) failed.
	at no.difi.certvalidator.rule.PrincipalNameRule.validate(PrincipalNameRule.java:64)
	at no.difi.certvalidator.structure.AndJunction.validate(AndJunction.java:23)
	at no.difi.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:35)
	at no.difi.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:12)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881)
	at no.difi.certvalidator.util.CachedValidatorRule.validate(CachedValidatorRule.java:29)
	at no.difi.certvalidator.ValidatorGroup.validate(ValidatorGroup.java:46)
	at no.difi.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:56)
	... 20 more

I assume this is a certificate issue, we are however able to transmit documents to other receivers without issue. Is this error caused on the receiving end or the transmitting end?

**Comment by klakegg** [comment]
This is caused by `no.difi.oxalis.api.lookup.LookupService`. The lookup service does not have neither a receiving end nor a transmitting end.

**Comment by klakegg** [comment]
Could you please point me to which of the information provided so far in this issue would make is possible for me to answer any of your questions?

**Comment by robrechtD** [comment]
We receive the information on the following page in our oxalis AP: http://b-e8579aca5fbcb469522b1347c0533720.iso6523-actorid-upis.edelivery.tech.ec.europa.eu/iso6523-actorid-upis%3A%3A9954%3A00000001002119687000/services/busdox-docid-qns%3A%3Aurn%3Aoasis%3Anames%3Aspecification%3Aubl%3Aschema%3Axsd%3AInvoice-2%3A%3AInvoice%23%23urn%3Awww.cenbii.eu%3Atransaction%3Abiitrns010%3Aver2.0%3Aextended%3Aurn%3Awww.peppol.eu%3Abis%3Apeppol4a%3Aver2.0%3Aextended%3Aurn%3Awww.simplerinvoicing.org%3Asi%3Asi-ubl%3Aver1.1.x%3A%3A2.1 

After releasing the connection, the peppol lookup service fails to validate the subject principal, resulting in the exception. 
The only activity between releasing the connection and the exception are the ones below.

2018-10-04 11:13:08,039 DEBUG [no.difi.vefa.peppol.lookup.util.XmlUtils] [] Root element: ns3:SignedServiceMetadata xmlns:ns3="http://busdox.org/serviceMetadata/publishing/1.0/" xmlns="http://busdox.org/transport/identifiers/1.0/" xmlns:ns2="http://www.w3.org/2005/08/addressing" xmlns:ns4="http://www.w3.org/2000/09/xmldsig#" 
2018-10-04 11:13:08,039 DEBUG [no.difi.vefa.peppol.lookup.util.XmlUtils] [] Namespace: ns3 
2018-10-04 11:13:08,039 DEBUG [no.difi.vefa.peppol.lookup.util.XmlUtils] [] xmlns:ns3="http://busdox.org/serviceMetadata/publishing/1.0/" 

We are on oxalis 4.0.0 in our production environment and currently using pki V2 certificates. 

Do you need any more information or are you unable to help me? 

Kind regards

**Comment by iPriyanshuRanjan** [comment]
When sending a document through oxalis we receive the following Exception:

2024-06-20 15:34:06 INFO  [main] n.o.o.t.MessageSenderFactory - Prioritized list of transport profiles:
2024-06-20 15:34:06 INFO  [main] n.o.o.t.MessageSenderFactory - => peppol-transport-as4-v2_0
2024-06-20 15:34:06 INFO  [main] n.o.o.t.MessageSenderFactory - => busdox-transport-as2-ver1p0r1
2024-06-20 15:34:06 INFO  [main] n.o.o.t.MessageSenderFactory - => busdox-transport-as2-ver2p0
2024-06-20 15:34:06 INFO  [main] n.o.o.t.MessageSenderFactory - => busdox-transport-as2-ver1p0


2024-06-20 15:34:06 DEBUG [pool-1-thread-1] o.x.D.c.WindowsResolverConfigProvider - JNA not available
2024-06-20 15:34:06 DEBUG [pool-1-thread-1] o.x.D.c.JndiContextResolverConfigProvider$InnerJndiContextResolverConfigProvider - JNDI class: javax.naming.directory.DirContext
2024-06-20 15:34:07 DEBUG [pool-1-thread-1] o.x.D.c.JndiContextResolverConfigProvider$InnerJndiContextResolverConfigProvider - Added /8.8.8.8:53 to nameservers
2024-06-20 15:34:07 DEBUG [pool-1-thread-1] o.x.D.c.JndiContextResolverConfigProvider$InnerJndiContextResolverConfigProvider - Added /8.8.4.4:53 to nameservers

Message failed : Validation of subject principal(CN) failed.

2024-06-20 15:34:07 ERROR [main] eu.sendregning.oxalis.Main - Execution failed: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at eu.sendregning.oxalis.Main.main(Main.java:245)
Caused by: network.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at network.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
	at network.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1

Process finished with exit code 1

Arguments passing:  oxalis-standalone -f C:\Users\invoice.xml --cert D:\Oxalis\Project\oxalis-standalone\cert.p12 --protocol peppol-transport-as4-v2_0 -d urn:oasis:names:specification:ubl:schema:xsd:Invoice-2::Invoice##urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0::2.1 -p urn:www.cenbii.eu:profile:bii01:ver2.0 -s 0195:sg1000000001_c1 -r 0195:sg1000000002_c4 

Please suggest how we resolve this issue.
