### ISSUE TITLE
Impossible to send to my AP (Execution failed: java.lang.ClassCastException: java.lang.String cannot be cast to javax.mail.internet.MimeMultipart)

### ISSUE THREAD

**Issue by cook32** [difi/oxalis#370]
I am unable to fix this issue, could you please help me ?

here is the output of the error :

2018-10-12 08:55:30,047 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /opt/tomcat9/oxalis 
2018-10-12 08:55:30,053 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /opt/tomcat9/oxalis/conf 
2018-10-12 08:55:30,053 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /opt/tomcat9/oxalis/conf/oxalis.conf 
2018-10-12 08:55:30,057 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Timestamp 
2018-10-12 08:55:30,059 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: system 
2018-10-12 08:55:30,059 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Evidence 
2018-10-12 08:55:30,060 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: rem 
2018-10-12 08:55:30,060 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: HTTP 
2018-10-12 08:55:30,060 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_TOTAL: 20 
2018-10-12 08:55:30,060 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => POOL_MAX_ROUTE: 2 
2018-10-12 08:55:30,061 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_CONNECT: 0 
2018-10-12 08:55:30,061 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TIMEOUT_READ: 0 
2018-10-12 08:55:30,061 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Error 
2018-10-12 08:55:30,061 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => TRACKER: quiet 
2018-10-12 08:55:30,061 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: AS2 
2018-10-12 08:55:30,061 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HOSTNAME:  
2018-10-12 08:55:30,062 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => NOTIFICATION: not.in.use@difi.no 
2018-10-12 08:55:30,062 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => MSGID_GENERATOR: default 
2018-10-12 08:55:30,062 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: File system 
2018-10-12 08:55:30,062 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => CONF: conf 
2018-10-12 08:55:30,062 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => INBOUND: /var/peppol/IN 
2018-10-12 08:55:30,063 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PLUGIN: plugin 
2018-10-12 08:55:30,063 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Key store 
2018-10-12 08:55:30,063 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PATH: /opt/tomcat9/oxalis/conf/oxalis-keystore.jks 
2018-10-12 08:55:30,063 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PASSWORD: ******* 
2018-10-12 08:55:30,063 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_ALIAS: *******
2018-10-12 08:55:30,064 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => KEY_PASSWORD: *****
2018-10-12 08:55:30,064 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Header 
2018-10-12 08:55:30,064 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PARSER: sbdh 
2018-10-12 08:55:30,064 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Persister 
2018-10-12 08:55:30,064 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => PAYLOAD: default 
2018-10-12 08:55:30,065 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => RECEIPT: default 
2018-10-12 08:55:30,065 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HANDLER: default 
2018-10-12 08:55:30,065 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tracing 
2018-10-12 08:55:30,065 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => REPORTER: noop 
2018-10-12 08:55:30,065 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => HTTP: null 
2018-10-12 08:55:30,065 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transformer 
2018-10-12 08:55:30,066 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => DETECTOR: legacy 
2018-10-12 08:55:30,066 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => WRAPPER: xml 
2018-10-12 08:55:30,066 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Statistics 
2018-10-12 08:55:30,066 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: noop 
2018-10-12 08:55:30,066 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Transmission 
2018-10-12 08:55:30,066 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => VERIFIER: default 
2018-10-12 08:55:30,067 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Logging 
2018-10-12 08:55:30,067 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => CONFIG: null 
2018-10-12 08:55:30,067 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => SERVICE: logback 
2018-10-12 08:55:30,067 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Settings: Tag 
2018-10-12 08:55:30,067 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] => GENERATOR: noop 
2018-10-12 08:55:30,078 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2018-10-12 08:55:30,078 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2018-10-12 08:55:30,078 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 
2018-10-12 08:55:31,518 INFO [no.difi.oxalis.commons.mode.ModeModule] Detected mode: TEST 

2018-10-12 08:55:32,429 INFO [eu.sendregning.oxalis.Main] Using 10 threads 
2018-10-12 08:55:34,302 ERROR [no.difi.oxalis.commons.error.QuietErrorTracker] [0f2b14ae-0118-47fb-9f4b-2782932411cf] java.lang.String cannot be cast to javax.mail.internet.MimeMultipart 
java.lang.ClassCastException: java.lang.String cannot be cast to javax.mail.internet.MimeMultipart
	at no.difi.oxalis.as2.util.SMimeReader.<init>(SMimeReader.java:55)
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:278)
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:233)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:149)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:135)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:87)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-10-12 08:55:34,318 ERROR [eu.sendregning.oxalis.Main] Execution failed: java.lang.ClassCastException: java.lang.String cannot be cast to javax.mail.internet.MimeMultipart 
java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.lang.String cannot be cast to javax.mail.internet.MimeMultipart
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:221)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to javax.mail.internet.MimeMultipart
	at no.difi.oxalis.as2.util.SMimeReader.<init>(SMimeReader.java:55)
	at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:278)
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:233)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:149)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:135)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:87)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Total time spent: 1s
Attempted to send 0 files
Failed transmissions: 1

**Comment by cook32** [comment]
Any idea ?
Help would be appreciated ;)

Thanks

**Comment by cook32** [comment]
Finally I found the problem which was linked to :
1) The SMP (Phoss) Endpoint url definition to Oxalis AP did not contain as2 at the end...
2) Bouncy Castle Provider needed to be added in java.security file under $JAVA_HOME/jre/lib/security/
=> Added this line : security.provider.N=org.bouncycastle.jce.provider.BouncyCastleProvider
