### ISSUE TITLE
Transmission failed while sending test file

### ISSUE THREAD

**Issue by thebilge** [difi/oxalis#384]
I am trying to send a test file from our outbound service and the receiver's access point is registered as our inbound service. Both inbound and outbound services are in test environment with test certificates. So no error on SMP lookup and initial connection. Outbound is sending the document but then it is getting "I/O error: Read timed out" and closing the connection. I tried to increase read time out property for inbound, not worked. Here is the logs:

```
DEBUG 2584 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-1 >> "AgkoVT/e/0Fo2BQAAAAAAAA=[\r][\n]"
DEBUG 2584 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-1 >> "------=_Part_1_1781214741.1542036487419--[\r][\n]"
DEBUG 2584 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-1 >> "[\r][\n]"
DEBUG 2584 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-1 >> "0[\r][\n]"
DEBUG 2584 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-1 >> "[\r][\n]"
DEBUG 2584 --- [pool-3-thread-1] org.apache.http.wire                     : http-outgoing-1 << "[read] I/O error: Read timed out"
DEBUG 2584 --- [pool-3-thread-1] h.i.c.DefaultManagedHttpClientConnection : http-outgoing-1: Close connection
DEBUG 2584 --- [pool-3-thread-1] h.i.c.DefaultManagedHttpClientConnection : http-outgoing-1: Shutdown connection
DEBUG 2584 --- [pool-3-thread-1] o.a.http.impl.execchain.MainClientExec   : Connection discarded
DEBUG 2584 --- [pool-3-thread-1] h.i.c.PoolingHttpClientConnectionManager : Connection released: [id: 1][route: {s}->https://peppol-test.itella.net:443][total kept alive: 1; route allocated: 0 of 2; total allocated: 1 of 20]
WARN 2584 --- [pool-3-thread-1] c.o.p.o.controller.OutboundController    : Sending of the message \test\peppol-bis.xml failed with I/O error: Transmission failed to endpoint 'https://peppol-test.itella.net/as2'.
WARN 2584 --- [pool-3-thread-1] c.o.p.c.e.oxalis.OxalisErrorRecognizer   : Failed to recognize error message: Transmission failed to endpoint 'https://peppol-test.itella.net/
INFO 2584 --- [pool-3-thread-1] c.o.p.o.controller.OutboundController    : Exception of type OTHER_ERROR registered as non-retriable, rejecting message \test\peppol-bis.xml
no.difi.oxalis.api.lang.OxalisTransmissionException: Transmission failed to endpoint 'https://peppol-test.itella.net/as2'.
	at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:244)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:149)
```

Any advice would be appreciated.

**Comment by artjomsk** [comment]
Try to increase both timeouts in oxalis.conf:
```
 oxalis.http {
	timeout.connect = 10000
	timeout.read = 10000
 }
```
