### ISSUE TITLE
javax.mail.internet.ParseException: Expected ';', got ":": Facing Critical issue after Oxalis upgrade to Oxalis 4.0.2 and PKI v3 cert

### ISSUE THREAD

**Issue by aaron-kumar** [difi/oxalis#393]
We are facing Critical issue after Oxalis upgrade to Oxalis 4.0.2 and PKI v3 cert.

Error trace:
06:56:01.173 [http-nio-8080-exec-5] ERROR n.d.o.c.error.QuietErrorTracker - [f37063e1-94bb-4a1a-b8c0-58c28781ed35] Expected ';', got ":"
javax.mail.internet.ParseException: Expected ';', got ":"
        at javax.mail.internet.ParameterList.<init>(ParameterList.java:292)
        at javax.mail.internet.ContentType.<init>(ContentType.java:114)
        at javax.mail.internet.MimeMultipart.parsebm(MimeMultipart.java:796)
        at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:503)
        at javax.mail.internet.MimeMultipart.getBodyPart(MimeMultipart.java:257)
        at no.difi.oxalis.as2.util.SMimeReader.<init>(SMimeReader.java:58)
        at no.difi.oxalis.as2.inbound.As2Servlet.doPost(As2Servlet.java:153)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by aaron-kumar** [comment]
It was certificate linking issue with AP URL in SMP.

**Comment by aaron-kumar** [comment]
This issue is still valid and we are facing this issue with on couple of APs

**Comment by klakegg** [comment]
This issue will be closed tomorrow unless information needed to reproduce the issue is provided.

**Comment by klakegg** [comment]
1. Issue is called a "critical issue".
2. Absolutely no information on how to reproduce the issue is provided.
3. Simple guesswork is provided when information is requested.

Conclusion: This issue is clearly not critical enough to provide information on how to reproduce it, which shows a pattern of issues reported by @aaron-kumar. To me this looks very much like intentional noise.

**Comment by aaron-kumar** [comment]
How to reproduce issue:
Try sending message using older Oxalis version i.e Oxalis 3.2.0 to Oxalis 4.0.2 , you will get same issue. 
There are APs which are still using older oxalis version and are not willing to upgrade. This issue is also happening with AP using custom library. 

Problem:
Problem is happening "SMimeReader" class while creating constructor object. Extra ":" character appending at the end of mime message is causing exception. Because of of this exception, control goes to exception handling block part of method "doPost" of class "As2Servlet". Here it tries to generate negative MDN but again fails because it again try to create "SMimeReader" constructor and met with same fate. So at end return 500 -internal server error instead of Negative MDN.
