### ISSUE TITLE
BLOCKER: Oxalis 4.0.2 blocking exchange of the documents from APs using older implemntations e.g. oxalis 3.2 or custom to APs using oxalis 4.0 and returns 500 internal error without sending proper -negative MDN

### ISSUE THREAD

**Issue by ManjeetYadav** [difi/oxalis#400]
After we upgraded our PEPPOL AP to oxalis 4.0, some access points using older oxalis versions e.g. 3.2 or 3.1 and some using custom implementations like access points hosted by Tickstar started getting internal 500 error without proper -ve MDN

This behavior doesn't seems in accordance to PEPPOL rules as a negative MDN should be sent back explaining the error instead of just 500 internal error according to peppol rules to the best of our understanding.

Getting proper reason of rejection in MDN helps sending AP to know the exact issue for correcting it or to debate if the receiving AP implementation is breaking the PEPPOL rules and sending -ve MDN incorrectly for the given situation.

**Comment by ManjeetYadav** [comment]
Additional details based on our analysis to help in decision making whether the issue needs to be fixed in sending AP library or receiving AP library.

We noticed that while sending from older PEPPOL implementations like oxalis 3.1, oxalis 3.2 or custom implementations like from tickstar, there is a colon at the end of content-type in the headers, see below

[http-nio-8080-exec-3] DEBUG n.difi.oxalis.as2.inbound.As2Servlet - => content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1;	boundary="----=_Part_1_300983713.1544165356458":

However unlike older oxalis implementations or custom implementations, it seems that oxalis 4.0.2 is expecting a semi colon (;) at the end of line here instead of colon (:) and throws following error:

[http-nio-8080-exec-3] ERROR n.d.o.c.error.QuietErrorTracker - [878e0cbd-b1f1-4bfc-a497-9700526c303a] Expected ';', got ":"
javax.mail.internet.ParseException: Expected ';', got ":"
	at javax.mail.internet.ParameterList.<init>(ParameterList.java:292)
	at javax.mail.internet.ContentType.<init>(ContentType.java:114)
	at javax.mail.internet.MimeMultipart.parsebm(MimeMultipart.java:796)
	at javax.mail.internet.MimeMultipart.parse(MimeMultipart.java:503)
	at javax.mail.internet.MimeMultipart.writeTo(MimeMultipart.java:428)
	at no.difi.oxalis.as2.util.SMimeReader.<init>(SMimeReader.java:64)
	at no.difi.oxalis.as2.inbound.As2Servlet.doPost(As2Servlet.java:172)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

This issue has been faced by access points who upgraded to oxalis 4.0 and who also used to receive from APs who are still using older versions.

Question: Why the new oxalis 4.0 break this working thing? Is it intentional? Are older oxalis versions e.g. 3.1. or 3.2 and custom implementations like tickstar not following the peppol interoperability standard or the new oxalis version?  Would oxalis be fixed to rectify the issue or would older versions be decommissioned and custom implementations need to be changed?

**Comment by ManjeetYadav** [comment]
I expect oxalis team to fix the issue of generating a proper -ve MDN explaining the issue instead of internal 500 error.

For the actual issue that is preventing the exchange of documents from APs using older implementations to APs using oxalis 4.0, we need to know if the new oxalis 4.0 break this earlier working scenario due to mistake or due to some good enough reason? 
Are older oxalis versions e.g. 3.1. or 3.2 and custom implementations like tickstar not following the peppol interoperability standard or the new oxalis version?  
Would oxalis be fixed to rectify the issue or would older versions be decommissioned and custom implementations need to be changed?
Please treat this on priority, many thousands documents are stuck due to this problems between many APs.

**Comment by Tickstar** [comment]
> We noticed that while sending from older PEPPOL implementations like oxalis 3.1, oxalis 3.2 or custom implementations like from tickstar, there is a colon at the end of content-type in the headers, see below

> [http-nio-8080-exec-3]
>  DEBUG n.difi.oxalis.as2.inbound.As2Servlet - => content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1;	boundary="----=_Part_1_300983713.1544165356458":

Access Points hosted by Tickstar **do not** send a colon at the end of the content-type, as we explained in a conversation via e-mail on Sun Dec 9.  

This is what we send in the content-type:

`Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; boundary="----=_Part_3052_1941016063.1544277851339"`

As you can see, there is no colon at the end.

**Comment by ManjeetYadav** [comment]
Thank you Difi for giving it high priority and just in time response and inputs to sort out this matter. Highly appreciated by Basware!

As discussed over email chain Sending APs using older oxalis version or hosted by Tickstart doesn't colon and the it is not reproducible between oxalis 3.2 and oxalis 4.0, Basware released a workaround fix until the root cause is identified to resume the blocked exchange of documents between few impacted APs and Basware.

We have been in contact with AWS afterwards to find the root cause and below is the response from AWS support.
"“Thank you for contacting AWS Support. I understand you're seeing an additional colon appended to the end of your content-type header only when the request comes via an ALB. We have actually seen this behavior before and it happens when the client is sending multi line headers. If there's a CRLF detected in a header and the new line starts with either a tab or space character, the ALB will think there's a new header so will append a colon. You should be able to verify this if you perform a packet capture on the client machine and inspecting the HTTP header. ALB was designed according to RFC 7230 which deprecated the support for multi line headers [1], which explains why it only happens when the request comes in via an ALB. Please consider having the client follow RFC 7230 standards while sending requests to an ALB.

RFC 2616 specifications supports multi-line headers.

Hope this helps you narrow down the issue but feel free to reach out to us again if you need clarification on anything.

--------------------------------------------------------
References:
[1] https://www.rfc-editor.org/rfc/pdfrfc/rfc7230.txt.pdf (page 80)”
"
