### ISSUE TITLE
Issues after migration to PKI V3 certificates Oxalis 3.2

### ISSUE THREAD

**Issue by rzvpopescu22** [difi/oxalis#401]
**Hello,**

**We have been running OK until now a Oxalis 3.2 based AP. We have changed the certificates to new ones (PKI V3) and we faced some issues. We solved the bug with the Regex pattern and also the new keystore looks ok.**

**Below is the error we are receiving:**

**We have also checked if running on TEST mode in the configuration file. I know that there was another opened github issue with similar error that was due to mixing PROD certificates with TEST conf. We are running with TEST certificates with TEST configuration**

**Is anybody using Oxalis 3.2 with new certificates? Do you have any suggestion for the below probem?**

**Thanks**

18-12-13 09:59:01,063 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Message-Id=<1544691540999.54.612227549.Oxalis@f64abdbef1ed> 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : MIME-Version=1.0 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Content-Type=multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; boundary="----=_Part_183_353632100.1544691541000" 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : AS2-From=PNO000001 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : AS2-To=POP000123 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Disposition-Notification-To=not.in.use@difi.no 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Disposition-Notification-Options=signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : AS2-Version=1.0 
2018-12-13 09:59:01,064 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Subject=AS2 message from Oxalis 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Date=Thu, 13 Dec 2018 08:59:01 +0000 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Content-Length=10050 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : User-Agent=Oxalis 4.0.4-SNAPSHOT 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Cipher-Version=TLSv1.2 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Cipher-Name=ECDHE-XXXXXXXXXXXX
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Cipher-Size=128 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Client-IP=93.94.10.XXX 
2018-12-13 09:59:01,065 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : X-Forwarded-Proto=https 
2018-12-13 09:59:01,066 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : X-Forwarded-For=93.94.10.XXX 
2018-12-13 09:59:01,066 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : X-Forwarded-Population=External 
2018-12-13 09:59:01,066 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Accept-Encoding=identity 
2018-12-13 09:59:01,066 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : Connection=Keep-Alive 
2018-12-13 09:59:01,066 DEBUG [eu.peppol.inbound.server.AS2Servlet] [] HTTP-Header : X-BlueCoat-Via=c5f0cc8deeXXXXXX 
2018-12-13 09:59:01,067 DEBUG [eu.peppol.as2.InboundMessageReceiver] [] Receiving message .. 
2018-12-13 09:59:01,097 DEBUG [eu.peppol.as2.As2DispositionNotificationOptions] [] Inspecting signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1 
2018-12-13 09:59:01,106 DEBUG [eu.peppol.as2.InboundMessageReceiver] [] Message contains valid Disposition-notification-options, now creating internal AS2 message... 
2018-12-13 09:59:01,134 DEBUG [eu.peppol.as2.As2DispositionNotificationOptions] [] Inspecting signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1 
2018-12-13 09:59:01,137 DEBUG [eu.peppol.as2.As2DispositionNotificationOptions] [] Inspecting signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1 
2018-12-13 09:59:01,151 DEBUG [eu.peppol.as2.InboundMessageReceiver] [] Validating AS2 Message: As2Message{mimeMessage=javax.mail.internet.MimeMessage@5e7e2559, as2Version='1.0', as2From=PNO000001, as2To=POP000123, subject='AS2 message from Oxalis', transmissionId='<1544691540999.54.612227549.Oxalis@f64abdbef1ed>', date='Thu, 13 Dec 2018 08:59:01 +0000', dispositionNotificationOptions=signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1, receiptDeliveryOption='null'} 
2018-12-13 09:59:01,157 DEBUG [eu.peppol.as2.SignedMimeMessageInspector] [] Verifying javax.mail.internet.MimeMessage with content type text/plain 
2018-12-13 09:59:01,549 DEBUG [eu.peppol.as2.SignedMimeMessageInspector] [] Verify the certificate issuer : C=BE,O=OpenPEPPOL AISBL,OU=FOR TEST ONLY,CN=PEPPOL ACCESS POINT TEST CA - G2 
2018-12-13 09:59:01,590 ERROR [eu.peppol.as2.InboundMessageReceiver] [] Unexpected error: Unable to trust the signer : Trust anchor for certification path not found. 
java.lang.IllegalStateException: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:214) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.parseSignedMessage(SignedMimeMessageInspector.java:177) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.<init>(SignedMimeMessageInspector.java:75) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.As2MessageInspector.validate(As2MessageInspector.java:35) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:106) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.inbound.server.AS2Servlet.doPost(AS2Servlet.java:165) [_wl_cls_gen.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:751) [weblogic.server.merged.jar:12.1.3.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844) [weblogic.server.merged.jar:12.1.3.0.0]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3456) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3422) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120) [com.oracle.css.weblogic.security.wls_7.1.0.0.jar:CSS 7.1 0.0]
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263) [weblogic.server.merged.jar:12.1.3.0.0]
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(Unknown Source) ~[bcprov-jdk15on-1.49.jar:1.49.0]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:279) ~[na:1.7.0_97]
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:204) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	... 26 common frames omitted
2018-12-13 09:59:01,615 WARN [eu.peppol.inbound.server.AS2Servlet] [] AS2 reception error: ERROR: Unable to trust the signer : Trust anchor for certification path not found. 
eu.peppol.as2.ErrorWithMdnException: ERROR: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:161) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.inbound.server.AS2Servlet.doPost(AS2Servlet.java:165) ~[_wl_cls_gen.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:751) [weblogic.server.merged.jar:12.1.3.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844) [weblogic.server.merged.jar:12.1.3.0.0]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3456) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3422) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120) [com.oracle.css.weblogic.security.wls_7.1.0.0.jar:CSS 7.1 0.0]
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263) [weblogic.server.merged.jar:12.1.3.0.0]
Caused by: java.lang.IllegalStateException: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:214) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.parseSignedMessage(SignedMimeMessageInspector.java:177) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.<init>(SignedMimeMessageInspector.java:75) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.As2MessageInspector.validate(As2MessageInspector.java:35) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:106) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	... 22 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(Unknown Source) ~[bcprov-jdk15on-1.49.jar:1.49.0]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:279) ~[na:1.7.0_97]
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:204) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	... 26 common frames omitted
2018-12-13 09:59:01,615 WARN [eu.peppol.inbound.server.AS2Servlet] [] Returning negative MDN with explanatory message 
2018-12-13 09:59:01,845 ERROR [eu.peppol.inbound.server.AS2Servlet] [] Returned negative MDN : 
------=_Part_2_1599642067.1544691541712
Content-Type: multipart/report; report-type=disposition-notification; 
	boundary="----=_Part_0_1850161728.1544691541618"

------=_Part_0_1850161728.1544691541618
Content-Type: text/plain
Content-Transfer-Encoding: 7bit

The following headers were received:
Date: Thu, 13 Dec 2018 08:59:01 +0000
Message-Id: <1544691540999.54.612227549.Oxalis@f64abdbef1ed>
Subject: AS2 message from Oxalis
MIME-Version: 1.0
Content-Type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; boundary="----=_Part_183_353632100.1544691541000"
Host: 158.167.243.49:6467
AS2-From: PNO000001
AS2-To: POP000123
Disposition-Notification-To: not.in.use@difi.no
Disposition-Notification-Options: signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
AS2-Version: 1.0
User-Agent: Oxalis 4.0.4-SNAPSHOT
Cipher-Version: TLSv1.2
Cipher-Name: ECDHE-RSA-AES128-XXX-XXXX
Cipher-Size: 128
Client-IP: 93.94.10.XXX
X-Forwarded-Proto: https
X-Forwarded-For: 93.94.10.XXX
X-Forwarded-Population: External
Accept-Encoding: identity
Connection: Keep-Alive
X-BlueCoat-Via: c5f0cc8deea15600
Content-Length: 10050

The message sent to AS2 System id PNO000001 on Thu, 13 Dec 2018 09:59:01 +0100 with subject AS2 MDN as you requested has been received.
It has been processed 
The warning/error message is :
ERROR: Unable to trust the signer : Trust anchor for certification path not found.

------=_Part_0_1850161728.1544691541618
Content-Type: message/disposition-notification
Content-Transfer-Encoding: 7bit

Reporting-UA: Oxalis
Disposition: automatic-action/MDN-sent-automatically; processed/ERROR: Unable to trust the signer : Trust anchor for certification path not found.
Original-Recipient: rfc822; PNO000001
Final-Recipient: rfc822; PNO000001
Original-Message-ID: <1544691540999.54.612227549.Oxalis@f64abdbef1ed>

------=_Part_0_1850161728.1544691541618--

------=_Part_2_1599642067.1544691541712
Content-Type: application/pkcs7-signature; name=smime.p7s; smime-type=signed-data
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"
Content-Description: S/MIME Cryptographic Signature

MIAGCSqGSIb3DQEHAqCAMIACAQExCzAJBgUrDgMCGgUAMIAGCSqGSIb3DQEHAQAAoIAwggXLMIID
s6ADAgECAhBXV0ID1ogrEeCVUJwvuxaFMA0GCSqGSIb3DQEBCwUAMGsxCzAJBgNVBAYTAkJFMRkw
F..........................................................................
............................................................................
............................................................................
EYzrwOVqBoEMIwaj+smO2Z4FjXsdmZ/SmOfDmzRjbFa8Igp0Sz8icFq4wqjjUn86Z7b265OA4kYw
rfINHqW26LcAAAAAAAA=
------=_Part_2_1599642067.1544691541712--
 
eu.peppol.as2.ErrorWithMdnException: ERROR: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:161) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.inbound.server.AS2Servlet.doPost(AS2Servlet.java:165) ~[_wl_cls_gen.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:751) [weblogic.server.merged.jar:12.1.3.0.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844) [weblogic.server.merged.jar:12.1.3.0.0]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118) [guice-servlet-3.0.jar:na]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113) [guice-servlet-3.0.jar:na]
	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3456) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3422) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120) [com.oracle.css.weblogic.security.wls_7.1.0.0.jar:CSS 7.1 0.0]
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2280) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2196) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2174) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1632) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:256) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:311) [weblogic.server.merged.jar:12.1.3.0.0]
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:263) [weblogic.server.merged.jar:12.1.3.0.0]
Caused by: java.lang.IllegalStateException: Unable to trust the signer : Trust anchor for certification path not found.
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:214) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.parseSignedMessage(SignedMimeMessageInspector.java:177) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.SignedMimeMessageInspector.<init>(SignedMimeMessageInspector.java:75) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.As2MessageInspector.validate(As2MessageInspector.java:35) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	at eu.peppol.as2.InboundMessageReceiver.receive(InboundMessageReceiver.java:106) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	... 22 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	at org.bouncycastle.jce.provider.PKIXCertPathValidatorSpi.engineValidate(Unknown Source) ~[bcprov-jdk15on-1.49.jar:1.49.0]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:279) ~[na:1.7.0_97]
	at eu.peppol.as2.SignedMimeMessageInspector.validateCertificate(SignedMimeMessageInspector.java:204) ~[oxalis-as2-3.2.0-SNAPSHOT.jar:na]
	... 26 common frames omitted
2018-12-13 09:59:01,846 ERROR [eu.peppol.inbound.server.AS2Servlet] [] ---------- REQUEST ERROR INFORMATION ENDS HERE --------------

**Comment by monze** [comment]
We are running Oxalis 3.2 in both Production and Test.

From the error ''Unable to trust the signer : Trust anchor for certification path not found.'' I would say that you have forgot to include the new root certificates.


We have made two new jks, and added them here:

```
oxalis-commons\src\main\resources\truststore-production-v3.jks
oxalis-commons\src\main\resources\truststore-test-v3.jks
```

Then we have update the PeppolTrustStore.java file

```
    List<TrustStoreResource> resourceNamesFor(PkiVersion pkiVersion, OperationalMode operationalMode) {
        List<TrustStoreResource> trustStoresToLoad = new ArrayList<TrustStoreResource>();
        switch (operationalMode) {
            case TEST:
                trustStoresToLoad.add(TrustStoreResource.V2_TEST);
                trustStoresToLoad.add(TrustStoreResource.V3_TEST);
                break;
            
            case PRODUCTION:
                switch (pkiVersion) {
                    case V1:
                        trustStoresToLoad.add(TrustStoreResource.V2_TEST);
                        break;
                    case T:
                        trustStoresToLoad.add(TrustStoreResource.V2_TEST);
                        trustStoresToLoad.add(TrustStoreResource.V2_PRODUCTION);
                        break;
                    case V2:
                        trustStoresToLoad.add(TrustStoreResource.V2_PRODUCTION);
                        trustStoresToLoad.add(TrustStoreResource.V3_PRODUCTION);
                    case V3:
                        trustStoresToLoad.add(TrustStoreResource.V2_PRODUCTION);
                        trustStoresToLoad.add(TrustStoreResource.V3_PRODUCTION);
                        break;
                }
                break;
            default:
                throw new IllegalStateException("No configuration for operational mode " + operationalMode.name());
        }
        return trustStoresToLoad;
    }

    public  enum TrustStoreResource {
        V1("truststore.jks"),
        V2_TEST("truststore-test.jks"),
        V3_TEST("truststore-test-v3.jks"),
        V2_PRODUCTION("truststore-production.jks"),
        V3_PRODUCTION("truststore-production-v3.jks"),
        ;

        private final String resourceName;

        TrustStoreResource(String s) {
            this.resourceName = s;
        }

        public String getResourcename() {
            return resourceName;
        }
    }
```

It is not the most elegant way, but it works.

Jacob Mogensen
mySupply ApS
Denmark

**Comment by rzvpopescu22** [comment]
Hello,

Thanks for your fast response and support. 

Unfortunately I have already done that modification in the sense that I completely replaced the old trustore with the new one but still having the issue. Still digging. 

Regards,
Razvan
