### ISSUE TITLE
Setting up with Docker

### ISSUE THREAD

**Issue by midthun** [difi/oxalis#411]
Hi, I am trying to set this up using the Docker image at [https://hub.docker.com/r/difi/oxalis](https://hub.docker.com/r/difi/oxalis )

I am getting these errors: 

```
4.0.3: Pulling from difi/oxalis
ff3a5c916c92: Pulling fs layer
a8906544047d: Pulling fs layer
a790ae7377b0: Pulling fs layer
421ed1349643: Pulling fs layer
421ed1349643: Waiting
a8906544047d: Download complete
ff3a5c916c92: Verifying Checksum
ff3a5c916c92: Download complete
ff3a5c916c92: Pull complete
a8906544047d: Pull complete
421ed1349643: Download complete
a790ae7377b0: Verifying Checksum
a790ae7377b0: Download complete
a790ae7377b0: Pull complete
421ed1349643: Pull complete
Digest: sha256:9cd34aa1f17d0d8f68959e2d52f695f2f0efc69ec626592b7906106872a12360
Status: Downloaded newer image for difi/oxalis:4.0.3
Sending build context to Docker daemon   5.12kB
Step 1/2 : FROM difi/oxalis:4.0.3
 ---> 34bdcb5b7619
Step 2/2 : EXPOSE 8080
 ---> Running in 310c68cb5164
Removing intermediate container 310c68cb5164
 ---> f0f6b2b9037b
Successfully built f0f6b2b9037b
08:35:16,356 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
08:35:16,356 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
08:35:16,356 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/oxalis/lib-server/oxalis-server-4.0.3.jar!/logback.xml]
08:35:16,357 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
08:35:16,357 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/oxalis/lib-server/oxalis-inbound-4.0.3.jar!/logback.xml]
08:35:16,357 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/oxalis/lib-server/oxalis-server-4.0.3.jar!/logback.xml]
08:35:16,368 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@725bef66 - URL [jar:file:/oxalis/lib-server/oxalis-server-4.0.3.jar!/logback.xml] is not of type file
08:35:16,414 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
08:35:16,415 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
08:35:16,417 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
08:35:16,424 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
08:35:16,468 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache] to WARN
08:35:16,468 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.eclipse.jetty] to WARN
08:35:16,469 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [no.difi.oxalis.commons.settings] to INFO
08:35:16,469 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
08:35:16,469 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
08:35:16,469 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
08:35:16,470 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2aaf7cc2 - Registering current configuration as safe fallback point

2019-02-11 08:35:16,881  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /oxalis 
2019-02-11 08:35:16,885  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /oxalis/conf 
2019-02-11 08:35:16,885  INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /oxalis/conf/oxalis.conf 
2019-02-11 08:35:16,891  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF: conf 
2019-02-11 08:35:16,891  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound 
2019-02-11 08:35:16,891  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: plugin 
2019-02-11 08:35:17,469  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /oxalis 
2019-02-11 08:35:17,470  INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /oxalis/conf 
2019-02-11 08:35:17,470  INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /oxalis/conf/oxalis.conf 
2019-02-11 08:35:17,471  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20 
2019-02-11 08:35:17,472  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2 
2019-02-11 08:35:17,472  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0 
2019-02-11 08:35:17,473  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0 
2019-02-11 08:35:17,474  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet 
2019-02-11 08:35:17,474  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS2 => HOSTNAME:  
2019-02-11 08:35:17,475  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no 
2019-02-11 08:35:17,476  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS2 => MSGID_GENERATOR: default 
2019-02-11 08:35:17,477  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF: conf 
2019-02-11 08:35:17,477  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound 
2019-02-11 08:35:17,477  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: plugin 
2019-02-11 08:35:17,478  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PATH: oxalis-keystore.jks 
2019-02-11 08:35:17,478  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: changeit 
2019-02-11 08:35:17,478  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: ap 
2019-02-11 08:35:17,478  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: changeit 
2019-02-11 08:35:17,479  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh 
2019-02-11 08:35:17,480  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default 
2019-02-11 08:35:17,480  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default 
2019-02-11 08:35:17,480  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default 
2019-02-11 08:35:17,480  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default 
2019-02-11 08:35:17,481  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop 
2019-02-11 08:35:17,481  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: null 
2019-02-11 08:35:17,482  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop 
2019-02-11 08:35:17,483  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50 
2019-02-11 08:35:17,483  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50 
2019-02-11 08:35:17,483  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Jetty => PORT: 8080 
2019-02-11 08:35:17,484  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Jetty => CONTEXT_PATH: / 
2019-02-11 08:35:17,484  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Jetty => SHUTDOWN_TOKEN: null 
2019-02-11 08:35:17,485  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Jetty => STOP_TIMEOUT: 10000 
2019-02-11 08:35:17,485  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop 
2019-02-11 08:35:17,486  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system 
2019-02-11 08:35:17,486  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem 
2019-02-11 08:35:17,487  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: legacy 
2019-02-11 08:35:17,487  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml 
2019-02-11 08:35:17,488  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop 
2019-02-11 08:35:17,488  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default 
2019-02-11 08:35:17,489  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: null 
2019-02-11 08:35:17,489  INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback 
2019-02-11 08:35:17,498  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles: 
2019-02-11 08:35:17,498  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1 
2019-02-11 08:35:17,498  INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0 
2019-02-11 08:35:17,510  WARN [no.difi.oxalis.sniffer.document.NoSbdhParser] You have enabled support for automatic detection of content. This functionality will be turned of by default in version 4.1 and removed in version 4.2/5.0. Use configuration "oxalis.transformer.detector = noop" to disable it today. 
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:

1) Error in custom provider, no.difi.oxalis.api.lang.OxalisLoadingException: Unable to find keystore at '/oxalis/conf/oxalis-keystore.jks'.
  at no.difi.oxalis.commons.security.CertificateModule.getKeyStore(CertificateModule.java:55)
  while locating java.security.KeyStore
    for the 1st parameter of no.difi.oxalis.commons.security.CertificateModule.getCertificate(CertificateModule.java:86)
  at no.difi.oxalis.commons.security.CertificateModule.getCertificate(CertificateModule.java:86)
  while locating java.security.cert.X509Certificate
    for the 1st parameter of no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:74)
  at no.difi.oxalis.commons.mode.ModeModule.providesMode(ModeModule.java:74)
  while locating no.difi.vefa.peppol.mode.Mode
    for the 1st parameter of no.difi.oxalis.outbound.lookup.LookupModule.getLookupService(LookupModule.java:57)
  at no.difi.oxalis.outbound.lookup.LookupModule.getLookupService(LookupModule.java:57)
  while locating no.difi.oxalis.api.lookup.LookupService
    for the 4th parameter of no.difi.oxalis.outbound.transmission.DefaultTransmitter.<init>(DefaultTransmitter.java:76)
  while locating no.difi.oxalis.outbound.transmission.DefaultTransmitter
  at no.difi.oxalis.outbound.transmission.TransmissionModule.configure(TransmissionModule.java:49)
  while locating no.difi.oxalis.api.outbound.Transmitter
Caused by: no.difi.oxalis.api.lang.OxalisLoadingException: Unable to find keystore at '/oxalis/conf/oxalis-keystore.jks'.
        at no.difi.oxalis.commons.security.CertificateModule.getKeyStore(CertificateModule.java:59)
        at no.difi.oxalis.commons.security.CertificateModule$$FastClassByGuice$$bb8feeb2.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:67)
        at no.difi.oxalis.server.Main.main(Main.java:58)

2) Error in custom provider, no.difi.oxalis.api.lang.OxalisLoadingException: Unable to find keystore at '/oxalis/conf/oxalis-keystore.jks'.
  at no.difi.oxalis.commons.security.CertificateModule.getKeyStore(CertificateModule.java:55)
  while locating java.security.KeyStore
    for the 1st parameter of no.difi.oxalis.commons.security.CertificateModule.getPrivateKeyEntry(CertificateModule.java:70)
  at no.difi.oxalis.commons.security.CertificateModule.getPrivateKeyEntry(CertificateModule.java:70)
  while locating java.security.PrivateKey
    for the 1st parameter of no.difi.oxalis.as2.util.SMimeMessageFactory.<init>(SMimeMessageFactory.java:75)
  at no.difi.oxalis.as2.util.SMimeMessageFactory.class(SMimeMessageFactory.java:68)
  while locating no.difi.oxalis.as2.util.SMimeMessageFactory
    for the 2nd parameter of no.difi.oxalis.as2.inbound.As2Servlet.<init>(As2Servlet.java:80)
  at no.difi.oxalis.as2.inbound.As2Servlet.class(As2Servlet.java:66)
  while locating no.difi.oxalis.as2.inbound.As2Servlet
  at no.difi.oxalis.as2.inbound.As2InboundModule.configureServlets(As2InboundModule.java:41)
  while locating javax.servlet.http.HttpServlet annotated with @com.google.inject.name.Named(value=oxalis-as2)
Caused by: no.difi.oxalis.api.lang.OxalisLoadingException: Unable to find keystore at '/oxalis/conf/oxalis-keystore.jks'.
        at no.difi.oxalis.commons.security.CertificateModule.getKeyStore(CertificateModule.java:59)
        at no.difi.oxalis.commons.security.CertificateModule$$FastClassByGuice$$bb8feeb2.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:67)
        at no.difi.oxalis.server.Main.main(Main.java:58)

2 errors
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:543)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:67)
        at no.difi.oxalis.server.Main.main(Main.java:58)
```

Is there any documentation on how to set this up using Docker? Forgive me if I am missing something obvious.

**Comment by arnemorten** [comment]
You need to mount volume so the image can see your keystore and configuration. 

From DockerFile.
` VOLUME /oxalis/conf /oxalis/ext /oxalis/inbound /oxalis/outbound /oxalis/plugin`

These are the intended mount points as far as I can see.

**Comment by midthun** [comment]
@arnemorten Thank you for the quick reply, I think this will solve my issue indeed.
