### ISSUE TITLE
OxalisAs2Exception: Content is not 'multipart/signed'

### ISSUE THREAD

**Issue by ig2503** [difi/oxalis#420]
Hi Oxalis team,
we are facing an issue reported from our receive who is using  Oxalis 4.04 software. Our receiver  is not able to interpret incoming AS2 message. The error is happening on this place in code:
![OxalisAS2](https://user-images.githubusercontent.com/46480373/60812510-eec92400-a191-11e9-940c-cd3c125c5303.png)

Here is the sent message header:

content-disposition = attachment; filename="smime.p7m"
as2-from = PNLXXX
connection = close, TE
ediint-features = multiple-attachments, CEM
date = Mon, 08 Jul 2019 13:51:20 CEST
as2-to = PNLXXX
disposition-notification-to = http://www.company.com:8080/as2/HttpReceiver
message-id = <mendelson_opensource_AS2-1562586675663-7@PNL000237_PNL000066>
subject = AS2 message
from = as2@company.com
as2-version = 1.2
disposition-notification-options = signed-receipt-protocol=optional, pkcs7-signature; signed-receipt-micalg=optional, sha-256
content-type =  multipart/signed; protocol="application/pkcs7-signature"; micalg=sha256;  boundary="----=_Part_26_581454225.1562586680199"
host = test.simplerinvoicing.org:443
mime-version = 1.0
recipient-address = https://test.simplerinvoicing.org/as2

Here is the raw data:

------=_Part_26_581454225.1562586680199
Content-Type: application/xml
Content-Transfer-Encoding: binary
Content-Disposition: attachment; filename=pyaload.XML

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

------=_Part_26_581454225.1562586680199
Content-Type: application/pkcs7-signature; name=smime.p7s; smime-type=signed-data
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="smime.p7s"
Content-Description: S/MIME Cryptographic Signature

------=_Part_26_581454225.1562586680199--

Oxalis doesn't report any error details but sends back just 500 Error. 

Could you please investigate this issue and let us know what is the problem in AS2 message?

Best regards,

**Comment by phax** [comment]
The source of the error might be this:
```
019-07-03 15:51:55,939 <mendelson_opensource_AS2-1562169114591-2@mycompanyAS2_PNL000177>
ERROR [no.difi.oxalis.commons.error.QuietErrorTracker] [4b279105-fcad-4695-8316-fe466d03ec20] javax.mail.util.SharedByteArrayInputStream cannot be cast to javax.mail.internet.MimeMultipart 
java.lang.ClassCastException: javax.mail.util.SharedByteArrayInputStream cannot be cast to javax.mail.internet.MimeMultipart
                at no.difi.oxalis.as2.util.SMimeReader.<init>(SMimeReader.java:55)
                at no.difi.oxalis.as2.inbound.As2InboundHandler.receive(As2InboundHandler.java:126)
                at no.difi.oxalis.as2.inbound.As2Servlet.doPost(As2Servlet.java:138)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
```
