### ISSUE TITLE
ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.

### ISSUE THREAD

**Issue by ign404** [difi/oxalis#421]
ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Unable to verify certificate of receiving access point.
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:162)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: no.difi.vefa.peppol.security.lang.PeppolSecurityException: Validation of subject principal(CN) failed.
        at no.difi.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:64)
        at no.difi.oxalis.commons.mode.OxalisCertificateValidator.perform(OxalisCertificateValidator.java:48)
        at no.difi.oxalis.commons.mode.OxalisCertificateValidator.validate(OxalisCertificateValidator.java:38)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:127)
        ... 10 common frames omitted
Caused by: no.difi.certvalidator.api.FailedValidationException: Validation of subject principal(CN) failed.
        at no.difi.certvalidator.rule.PrincipalNameRule.validate(PrincipalNameRule.java:68)
        at no.difi.certvalidator.structure.AndJunction.validate(AndJunction.java:29)
        at no.difi.certvalidator.structure.AbstractJunction.validate(AbstractJunction.java:36)
        at no.difi.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:43)
        at no.difi.certvalidator.util.CachedValidatorRule.load(CachedValidatorRule.java:13)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
        at no.difi.certvalidator.util.CachedValidatorRule.validate(CachedValidatorRule.java:30)
        at no.difi.certvalidator.util.CachedValidatorRule.validate(CachedValidatorRule.java:35)
        at no.difi.certvalidator.ValidatorGroup.validate(ValidatorGroup.java:79)
        at no.difi.certvalidator.ValidatorGroup.validate(ValidatorGroup.java:70)
        at no.difi.vefa.peppol.security.util.DifiCertificateValidator.validate(DifiCertificateValidator.java:62)
        ... 13 common frames omitted
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1

**Comment by ign404** [comment]
help me fix this plss

**Comment by vinoddanekar** [comment]
Hi,
Can you please tell me how did you solve this issue?

Vinod
