### ISSUE TITLE
ERROR [no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 502 from https://test-aksesspunkt.difi.no/as2

### ISSUE THREAD

**Issue by ign404** [difi/oxalis#422]
ERROR [no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 502 from https://test-aksesspunkt.difi.no/as2
2019-09-06 14:19:16,524 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=502, contents received (164 characters): <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=502, contents received (164 characters): <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=502, contents received (164 characters): <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

        at no.difi.oxalis.as2.outbound.As2MessageSender.handleFailedRequest(As2MessageSender.java:347)
        at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:274)
        at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:246)
        at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:155)
        at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Total time spent: 29s
Attempted to send 0 files
Failed transmissions: 1

**Comment by ign404** [comment]
help fix plss

**Comment by tranthanhtam8890** [comment]
I got same problem. How can you resolved it ? Can help me please ?

**Comment by pekaaw** [comment]
We have the same problem as well. I found no solution here... Anyone?

**Comment by open-gdsn** [comment]
See https://github.com/difi/oxalis/issues/429

**Comment by AnandRameshBabu** [comment]
we have same issue while uploading a test XML using TEST certificate. Can anyone help us out to resolve this issue.
