### ISSUE TITLE
internal error 500 oxalis

### ISSUE THREAD

**Issue by andreaabbate** [difi/oxalis#427]
Hi,

when i test my oxalis installation i receve below error:

somone can help me to resolve ?

`/usr/java/jdk1.8.0_221/bin/java -jar /usr/share/oxalis-4.1.0/target/oxalis-standalone.jar -f /usr/share/oxalis-4.1.0/oxalis-legacy/oxalis-document-sniffer/src/test/resources/peppol-bis-invoice-sbdh.xml -u http://xxxx.xxxx.it:8082/oxalis-4.1.0/as2 -cert /usr/share/tomcat9/.oxalis/peppol.crt
`

```
2019-10-08 14:41:35,840 ERROR [no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 500 from http://xxxx.xxxx.it:8082/oxalis-4.1.0/as2
2019-10-08 14:41:35,847 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
        at no.difi.oxalis.as2.outbound.As2MessageSender.handleFailedRequest(As2MessageSender.java:351)
        at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:278)
        at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:247)
        at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:156)
        at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1`

**catalina.out**

`14:41:35.838 [http-nio-8082-exec-14] WARN  n.d.o.c.persist.DefaultPersister - Transmission 'null' failed duo to can't create content verifier: exception on setup: java.security.NoSuchAlgorithmException: class configured for Signature (provider: BC) cannot be found..
14:41:35.838 [http-nio-8082-exec-14] ERROR n.d.o.c.error.QuietErrorTracker - [afa2c363-1fa1-4346-8eb9-bb61b09c4440] null
java.lang.NullPointerException: null
        at java.nio.file.Files.provider(Files.java:97)
        at java.nio.file.Files.delete(Files.java:1126)
        at no.difi.oxalis.commons.persist.DefaultPersister.persist(DefaultPersister.java:104)
        at no.difi.oxalis.commons.persist.DefaultPersisterHandler.persist(DefaultPersisterHandler.java:76)
        at no.difi.oxalis.as2.inbound.As2InboundHandler.receive(As2InboundHandler.java:218)
        at no.difi.oxalis.as2.inbound.As2Servlet.doPost(As2Servlet.java:145)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
        at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
        at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
        at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
        at io.opentracing.contrib.web.servlet.filter.TracingFilter.doFilter(TracingFilter.java:189)
        at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
        at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
        at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
        at no.difi.oxalis.dist.war.WarGuiceFilter.doFilter(WarGuiceFilter.java:21)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:860)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - Request headers:
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => message-id: <1570538495684.1.-1045296628.Oxalis@XXXXX>
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => mime-version: 1.0
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => content-type: multipart/signed; protocol="application/pkcs7-signature"; micalg=sha-1; boundary="----=_Part_1_1644680645.1570538495727"
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => as2-from: PIT000329
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => as2-to: PIT000329
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => disposition-notification-to: not.in.use@difi.no
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => disposition-notification-options: signed-receipt-protocol=required,pkcs7-signature; signed-receipt-micalg=required,sha1
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => as2-version: 1.0
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => subject: AS2 message from Oxalis
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => date: Tue, 08 Oct 2019 14:41:35 +0200
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => content-length: 13605
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => host: XXXX.XXXX.it:8082
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => connection: Keep-Alive
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => user-agent: Oxalis 4.1.0
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet - => accept-encoding: gzip,deflate
14:41:35.839 [http-nio-8082-exec-14] ERROR n.difi.oxalis.as2.inbound.As2Servlet -
---------- REQUEST FAILURE INFORMATION ENDS HERE --------------
```

**oxalis and enviroment info**

version.oxalis: 4.1.0
version.java: 1.8.0_221
mode: TEST
certificate.subject: C=IT,O=xxxx,OU=PEPPOL TEST AP,CN=xxxxx
certificate.issuer: CN=PEPPOL ACCESS POINT TEST CA - G2,OU=FOR TEST ONLY,O=OpenPEPPOL AISBL,C=BE
certificate.expired: false
build.id: f1b100d5c22200193a5e1d02549115ff4eb6e495
build.tstamp: 18.09.2019 @ 10:43:22 UTC

Tomcat: 9.0.26

**Comment by ign404** [comment]
[no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 502 from https://test-aksesspunkt.difi.no/as2

also having this issue
please help fix

**Comment by ign404** [comment]
@klakegg sir can you help us fix this?

**Comment by klakegg** [comment]
`2019-10-08 14:41:35,840 ERROR [no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 500 from http://xxxx.xxxx.it` returning error **500** provided by @andreaabbate does not seem to be the same as `[no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 502 from https://test-aksesspunkt.difi.no/as2` returning error **502** provided by @ign404. What makes those cases the same?

According to the log:
```14:41:35.838 [http-nio-8082-exec-14] WARN  n.d.o.c.persist.DefaultPersister - Transmission 'null' failed duo to can't create content verifier: exception on setup: java.security.NoSuchAlgorithmException: class configured for Signature (provider: BC) cannot be found..```

There seem to be a problem related to dependencies or matching of algorithms.

**Comment by open-gdsn** [comment]
@klakegg : See https://github.com/difi/oxalis/issues/429 (@ign404  created a new issue which we encounter too)

**Comment by klakegg** [comment]
@open-gdsn : That is a different issue, thus is not relevant in this issue.

**Comment by open-gdsn** [comment]
Yes **I know** that is why I referred to the other issue and added comment there.
