### ISSUE TITLE
Oxalis doesn't find oxalis.conf

### ISSUE THREAD

**Issue by Luymara** [difi/oxalis#428]
Heyho,

so we try to set up PEPPOL using oxalis. We already passed the first test in the PEPPOL TestBed (receiving/Outbound), but at the second test (sending/Inbound) we get an exception. The oxalis.conf is set up in the right way, as far as I know.

So we open a docker, where the oxalis-standalone.jar gets executed. And then oxalis fails.

2019-10-10 13:50:09,683 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /oxalis
2019-10-10 13:50:09,688 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /oxalis
2019-10-10 13:50:09,688 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /oxalis/oxalis.conf
2019-10-10 13:50:09,693 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF:
2019-10-10 13:50:09,693 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound
2019-10-10 13:50:09,694 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: null
2019-10-10 13:50:10,637 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Home folder: /oxalis
2019-10-10 13:50:10,640 INFO [no.difi.oxalis.commons.filesystem.FileSystemModule] Configuration folder: /oxalis
2019-10-10 13:50:10,640 INFO [no.difi.oxalis.commons.config.ConfigModule] Configuration file: /oxalis/oxalis.conf
2019-10-10 13:50:10,640 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_TOTAL: 20
2019-10-10 13:50:10,641 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => POOL_MAX_ROUTE: 2
2019-10-10 13:50:10,641 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_CONNECT: 0
2019-10-10 13:50:10,641 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_READ: 0
2019-10-10 13:50:10,641 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] HTTP => TIMEOUT_SOCKET: 0
2019-10-10 13:50:10,641 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Error => TRACKER: quiet
2019-10-10 13:50:10,641 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] AS2 => NOTIFICATION: not.in.use@difi.no
2019-10-10 13:50:10,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => CONF:
2019-10-10 13:50:10,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => INBOUND: inbound
2019-10-10 13:50:10,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] File system => PLUGIN: null
2019-10-10 13:50:10,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Identifiers => HOSTNAME:
2019-10-10 13:50:10,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Identifiers => MSGID_GENERATOR: default
2019-10-10 13:50:10,642 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PATH: oxalis-keystore.jks
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => PASSWORD: changeit
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_ALIAS: ap
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Key store => KEY_PASSWORD: changeit
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Header => PARSER: sbdh
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => PAYLOAD: default
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => RECEIPT: default
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => EXCEPTION: default
2019-10-10 13:50:10,643 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Persister => HANDLER: default
2019-10-10 13:50:10,644 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => REPORTER: noop
2019-10-10 13:50:10,644 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => HTTP: null
2019-10-10 13:50:10,644 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tracing => TRACER: noop
2019-10-10 13:50:10,644 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => DEFAULT: 50
2019-10-10 13:50:10,644 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Executor => STATISTICS: 50
2019-10-10 13:50:10,644 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Tag => GENERATOR: noop
2019-10-10 13:50:10,646 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Timestamp => SERVICE: system
2019-10-10 13:50:10,646 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Evidence => SERVICE: rem
2019-10-10 13:50:10,646 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => DETECTOR: noop
2019-10-10 13:50:10,647 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transformer => WRAPPER: xml
2019-10-10 13:50:10,647 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Statistics => SERVICE: noop
2019-10-10 13:50:10,647 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Transmission => VERIFIER: default
2019-10-10 13:50:10,647 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => CONFIG: null
2019-10-10 13:50:10,648 INFO [no.difi.oxalis.commons.settings.SettingsBuilder] Logging => SERVICE: logback
2019-10-10 13:50:10,676 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] Prioritized list of transport profiles:
2019-10-10 13:50:10,678 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0r1
2019-10-10 13:50:10,678 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver2p0
2019-10-10 13:50:10,678 INFO [no.difi.oxalis.outbound.transmission.MessageSenderFactory] => busdox-transport-as2-ver1p0
2019-10-10 13:50:10,716 ERROR [no.difi.oxalis.commons.guice.GuiceModuleLoader] Unable to find keystore at '/oxalis/oxalis-keystore.jks'.
no.difi.oxalis.api.lang.OxalisLoadingException: Unable to find keystore at '/oxalis/oxalis-keystore.jks'.
        at no.difi.oxalis.commons.security.CertificateModule.getKeyStore(CertificateModule.java:67)
        at no.difi.oxalis.commons.security.CertificateModule$$FastClassByGuice$$bb8feeb2.invoke(<generated>)
        at com.google.inject.internal.ProviderMethod$FastClassProviderMethod.doProvision(ProviderMethod.java:264)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:52)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:124)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:66)
        at no.difi.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
        at eu.sendregning.oxalis.Main.main(Main.java:116)
Exception in thread "main" no.difi.oxalis.api.lang.OxalisLoadingException: Unable to load Oxalis due to errors during loading.
        at no.difi.oxalis.commons.guice.GuiceModuleLoader.initiate(GuiceModuleLoader.java:76)
        at no.difi.oxalis.outbound.OxalisOutboundComponent.<init>(OxalisOutboundComponent.java:45)
        at eu.sendregning.oxalis.Main.main(Main.java:116)

Hope you can help

Luymara

**Comment by Luymara** [comment]
Ok fixed it, we set up a new docker image which links directly to the right config
