### ISSUE TITLE
OxalisTransmissionException: No transmission is provided.

### ISSUE THREAD

**Issue by midhunmohan** [difi/oxalis#434]
Following log returned when try to execute the transfer by

> java -jar /opt/production/oxalis/target/oxalis-standalone.jar -f /home/ubuntu/out/3bc0bbc1-715f-4cd2-a7ba-72fa27f9edd1.doc.xml -r xxxx:xxxx1947xxxxR -s xxxx:xxxx20140xxxxG

```
Message failed : null

2019-10-31 05:45:55,844 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

 ```
oxalis.keystore {
     # Relative to OXALIS_HOME
     path=ProdCert.p12
     password = "*********"
     key.alias = "psg000206’s openpeppol aisbl id #2"
     key.password = "********"
 }
the production conf is as follows
 # The relative name of the directory holding plugin
 oxalis.path.plugin = oxalis-plugin

 # Signals to Oxalis that we should look for plugin
 #oxalis.persister.receipt = plugin

 # Where to store inbound files
 oxalis.path.inbound = /var/peppol/prod/IN

#loging
#oxalis.inbound.log.config = /var/log/peppol/inbound.log 

#lookup
#oxalis.sml.hostname = acc.edelivery.tech.ec.europa.eu

```
JDK Version Used: openjdk version "1.8.0_222"
Oxalis Version: 4.0
is there anything wrong in the transfer command or with the conf?

**Comment by napramirez** [comment]
At first glance, there doesn't seem to be any issues in the configuration. However, to allow for further investigation, please provide for the following:

- What is the patch version of Oxalis? (e.g. 4.0.4).
- Is the Oxalis instance built from source?
- Does it have any customizations?

**Comment by midhunmohan** [comment]
- the patch version of Oxalis -> **4.0.4-SNAPSHOT**
- Is the Oxalis instance built from source? **Yes**
- Does it have any customizations? **Nothing other than oxalis.conf as decribed above**
@napramirez

**Comment by midhunmohan** [comment]
After setting this in oxalis.conf
 `oxalis.transformer.detector=noop`

Message failed : Content does not contain SBDH.

this has been displayed, but in the xml we have the SBDH envelope

**Comment by artjomsk** [comment]
I don't think you should set `oxalis.transformer.detector=noop`

For me, when I add this to oxalis.conf I get the following error:

```
Message failed : Content does not contain SBDH.

2019-11-12 14:44:07,033 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
``` 

But without the line Oxalis 4.0.4 is working for me.

**Comment by midhunmohan** [comment]
@artjomsk , we are generating SBDH wrapper for the forward compliance. There its been recommended to use `oxalis.transformer.detector=noop` so that oxalis don't have to build/generate the same from the receiver and sender details provided via args.

**Comment by artjomsk** [comment]
OK, I see. Yes, when payload file contains SBDH recommended `oxalis.transformer.detector=noop` doesn't cause error.

Thank you for information. But you have some other problem I suppose.

**Comment by midhunmohan** [comment]
@artjomsk, @napramirez  finally found the point, there was two things caused these issues.

- DateTime format was not as expected,  we needed to use like this:
  `<CreationDateAndTime>2019-10-30T13:12:36.040Z</CreationDateAndTime>`
instead of

>      <DocumentIdentification>
>          <Standard>#########</Standard>
>          <TypeVersion>####</TypeVersion>
>          <InstanceIdentifier>########</InstanceIdentifier>
>          <Type>Invoice</Type>
>          <CreationDateAndTime>2019-10-30T13:12:36.040Z[Etc/UTC]</CreationDateAndTime>
>       </DocumentIdentification>

- Also following info was missing in the document 

>       <BusinessScope>
>          <Scope>
>             <Type>DOCUMENTID</Type>
>             <InstanceIdentifier>########</InstanceIdentifier>
>          </Scope>
>          <Scope>
>             <Type>PROCESSID</Type>
>             <InstanceIdentifier>########</InstanceIdentifier>
>          </Scope>
>       </BusinessScope>

Thanks for you valuable responses

**Comment by tbicego** [comment]
Hello,
my oxalis.conf is like the above one and I have this problem which is similar, what could the cause be?

`2024-04-10 17:16:07,620 WARN [no.difi.oxalis.sniffer.document.NoSbdhParser] [] You have enabled support for automatic detection of content. This functionality will be turned of by default in version 4.1 and removed in version 4.2/5.0. Use configuration "oxalis.transformer.detector = noop" to disable it today. 
2024-04-10 17:16:07,794 ERROR [eu.sendregning.oxalis.Main] [] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

I am using this line to run oxalis:

`/opt/app/java8/bin/java -classpath "oxalis-standalone-4.0.4.jar:/opt/app/Oxalis-AS4/*" eu.sendregning.oxalis.Main -f $file > $file.log;`

where all the libraries needed are in /opt/app/Oxalis-AS4/
