### ISSUE TITLE
I am trying to test my oxalis server by uploading sample xml to Difi's test access point

### ISSUE THREAD

**Issue by AnandRameshBabu** [difi/oxalis#451]
java -jar target/oxalis-standalone.jar \
     -f src/test/resources/BII04_T10_PEPPOL-v2.0_invoice.xml \
     -r 9908:810418052 \
     -s 9909:810418052

Message failed : Content does not contain SBDH.

2020-01-05 09:03:19,288 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided. 
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at eu.sendregning.oxalis.Main.main(Main.java:227)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
	at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
	at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Total time spent: 0s
Attempted to send 0 files
Failed transmissions: 1

**Comment by ahaaje** [comment]
I am getting the exact same error using the same command with Oxalis 4.1.1. The config file and keystore is read, but error message is the same `Message failed : Content does not contain SBDH`

Any pointer on how to fix it would be most appreciated.

**Comment by aaron-kumar** [comment]
Please wrap your document inside SBDH header (used for routing information, see SBDH / Envelope specifications for Peppol). Oxalis stopped wrapping in the recent versions, so you have to do it before Oxalis take it over for transmission.  Oxalis read details from SBDH header and then transmit document. Hope that clarify @AnandRameshBabu & @ahaaje

**Comment by vincentpwnz00r** [comment]
Hello I too faced the same error, what is the command to wrap the documnet in SBDH header? Thank you

**Comment by madhawaudayakantha** [comment]
Hi,

I hope the following is usefull.
You could externally use *oxalis-document-sniffer* dependency to wrap your
document payload with SBDH headers.
"no.difi.oxalis" % "oxalis-document-sniffer" % "4.0.2"

In SbdhWrapper class you could find the below method which does that.

public byte[] wrap(InputStream inputStream, Header headers)


Best Regards,

Madhawa.

**Comment by vincentpwnz00r** [comment]
Thanks for the reply, how do i specifically run the sbdhwrapper class as it is producing an error 

`Error: Could not find or load main class`

**Comment by madhawag** [comment]
@vincentpwnz00r Have you provided the oxalis-document-sniffer dependency externally. If so you could just call the SbdhWrapper.wrap(payloadStream, headers) method.

**Comment by madhawaudayakantha** [comment]
@vincentpwnz00r <https://github.com/vincentpwnz00r> Have you provided the
oxalis-document-sniffer dependency externally. If so you could just call
the SbdhWrapper.wrap(payloadStream, headers) method.
