### ISSUE TITLE
Time out on 4.1.1/AS4 4.1.3

### ISSUE THREAD

**Issue by RvanMaarenApro** [difi/oxalis#458]
Found this error this morning in the logs, it seems it is failing not consequently.

Log from oxalis:2020-02-13 09:05:50,168  DEBUG [no.difi.oxalis.as4.util.PolicyService] Policy classpath: /eDeliveryAS4Policy_BST.xml
Log from oxalis:2020-02-13 09:07:58,554  WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {oxalis.difi.no/}outbound-service#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
Log from oxalis:org.apache.cxf.binding.soap.SoapFault: Connection timed out (Connection timed out)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:221)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
Log from oxalis:        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:95)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:87)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
Log from oxalis:        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Log from oxalis:        at java.lang.Thread.run(Thread.java:748)
Log from oxalis:Caused by: com.ctc.wstx.exc.WstxIOException: Connection timed out (Connection timed out)

Previous transmission to same participant went fine on AS4.

Any thougths ?

Regards,

Richard

**Comment by RvanMaarenApro** [comment]
Full log :

Log from oxalis:2020-02-13 09:45:54,244  DEBUG [no.difi.oxalis.as4.util.PolicyService] Policy classpath: /eDeliveryAS4Policy_BST.xml
Log from oxalis:2020-02-13 09:48:02,778  WARN [org.apache.cxf.phase.PhaseInterceptorChain] Interceptor for {oxalis.difi.no/}outbound-service#{http://cxf.apache.org/jaxws/dispatch}Invoke has thrown exception, unwinding now
Log from oxalis:org.apache.cxf.binding.soap.SoapFault: Connection timed out (Connection timed out)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:221)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
Log from oxalis:        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:95)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:87)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
Log from oxalis:        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Log from oxalis:        at java.lang.Thread.run(Thread.java:748)
Log from oxalis:Caused by: com.ctc.wstx.exc.WstxIOException: Connection timed out (Connection timed out)
Log from oxalis:        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:471)
Log from oxalis:        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:770)
Log from oxalis:        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:716)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
Log from oxalis:        ... 24 common frames omitted
Log from oxalis:Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
Log from oxalis:        at java.net.PlainSocketImpl.socketConnect(Native Method)
Log from oxalis:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Log from oxalis:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Log from oxalis:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Log from oxalis:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Log from oxalis:        at java.net.Socket.connect(Socket.java:607)
Log from oxalis:        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
Log from oxalis:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
Log from oxalis:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
Log from oxalis:        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
Log from oxalis:        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
Log from oxalis:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
Log from oxalis:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
Log from oxalis:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
Log from oxalis:        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:274)
Log from oxalis:        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1343)
Log from oxalis:        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1304)
Log from oxalis:        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:307)
Log from oxalis:        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
Log from oxalis:        at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
Log from oxalis:        at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
Log from oxalis:        at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
Log from oxalis:        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
Log from oxalis:        at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
Log from oxalis:        at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:286)
Log from oxalis:        at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:600)
Log from oxalis:        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:469)
Log from oxalis:        ... 27 common frames omitted
Log from oxalis:2020-02-13 09:48:02,792  ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
Log from oxalis:java.util.concurrent.ExecutionException: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
Log from oxalis:        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
Log from oxalis:        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
Log from oxalis:        at eu.sendregning.oxalis.Main.main(Main.java:227)
Log from oxalis:Caused by: no.difi.oxalis.as4.lang.OxalisAs4TransmissionException: Failed to send message
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:98)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.send(As4MessageSender.java:87)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSenderFacade.send(As4MessageSenderFacade.java:20)
Log from oxalis:        at no.difi.oxalis.api.outbound.MessageSender.send(MessageSender.java:59)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
Log from oxalis:        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:168)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:96)
Log from oxalis:        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:49)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Log from oxalis:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Log from oxalis:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Log from oxalis:        at java.lang.Thread.run(Thread.java:748)
Log from oxalis:Caused by: javax.xml.ws.soap.SOAPFaultException: Connection timed out (Connection timed out)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.mapException(DispatchImpl.java:285)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:330)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:241)
Log from oxalis:        at no.difi.oxalis.as4.outbound.As4MessageSender.invoke(As4MessageSender.java:95)
Log from oxalis:        ... 14 common frames omitted
Log from oxalis:Caused by: org.apache.cxf.binding.soap.SoapFault: Connection timed out (Connection timed out)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:221)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:174)
Log from oxalis:        at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:530)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:441)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:356)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:314)
Log from oxalis:        at org.apache.cxf.endpoint.ClientImpl.invokeWrapped(ClientImpl.java:349)
Log from oxalis:        at org.apache.cxf.jaxws.DispatchImpl.invoke(DispatchImpl.java:322)
Log from oxalis:        ... 16 common frames omitted
Log from oxalis:Caused by: com.ctc.wstx.exc.WstxIOException: Connection timed out (Connection timed out)
Log from oxalis:        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:471)
Log from oxalis:        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:770)
Log from oxalis:        at org.apache.cxf.staxutils.StaxUtils.copy(StaxUtils.java:716)
Log from oxalis:        at org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor$SAAJOutEndingInterceptor.handleMessage(SAAJOutInterceptor.java:214)
Log from oxalis:        ... 24 common frames omitted
Log from oxalis:Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
Log from oxalis:        at java.net.PlainSocketImpl.socketConnect(Native Method)
Log from oxalis:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
Log from oxalis:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
Log from oxalis:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
Log from oxalis:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
Log from oxalis:        at java.net.Socket.connect(Socket.java:607)
Log from oxalis:        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
Log from oxalis:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
Log from oxalis:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
Log from oxalis:        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
Log from oxalis:        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
Log from oxalis:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1205)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
Log from oxalis:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
Log from oxalis:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
Log from oxalis:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:264)
Log from oxalis:        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.setupWrappedStream(URLConnectionHTTPConduit.java:274)
Log from oxalis:        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleHeadersTrustCaching(HTTPConduit.java:1343)
Log from oxalis:        at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.onFirstWrite(HTTPConduit.java:1304)
Log from oxalis:        at org.apache.cxf.transport.http.URLConnectionHTTPConduit$URLConnectionWrappedOutputStream.onFirstWrite(URLConnectionHTTPConduit.java:307)
Log from oxalis:        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:47)
Log from oxalis:        at org.apache.cxf.io.AbstractThresholdOutputStream.unBuffer(AbstractThresholdOutputStream.java:89)
Log from oxalis:        at org.apache.cxf.io.AbstractThresholdOutputStream.write(AbstractThresholdOutputStream.java:63)
Log from oxalis:        at org.apache.cxf.io.CacheAndWriteOutputStream.write(CacheAndWriteOutputStream.java:80)
Log from oxalis:        at org.apache.cxf.io.AbstractWrappedOutputStream.write(AbstractWrappedOutputStream.java:51)
Log from oxalis:        at com.ctc.wstx.io.UTF8Writer.write(UTF8Writer.java:143)
Log from oxalis:        at com.ctc.wstx.sw.BufferingXmlWriter.writeRaw(BufferingXmlWriter.java:286)
Log from oxalis:        at com.ctc.wstx.sw.BufferingXmlWriter.writeCharacters(BufferingXmlWriter.java:600)
Log from oxalis:        at com.ctc.wstx.sw.BaseStreamWriter.writeCharacters(BaseStreamWriter.java:469)
Log from oxalis:        ... 27 common frames omitted
Log from oxalis:Total time spent: 131s
Log from oxalis:Attempted to send 0 files
Log from oxalis:Failed transmissions: 1

**Comment by klakegg** [comment]
So, it went fine with AS4, and then you post an AS4 related stacktrace. Do you think it is something about AS2?

**Comment by RvanMaarenApro** [comment]
It seems to me some kind of network error but will post it also on the AS4 channel.

Thanks.
