### ISSUE TITLE
Message failed : Received code 400 for lookup.

### ISSUE THREAD

**Issue by SkyTradeInc** [difi/oxalis#466]
I am attempting to send an invoice on TEST mode to receiver  0151:11111111138 as requested by the ATO for passing the interoperability test.

Here is the participant information
https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0151%3A11111111138&sml=auto&querybc=true&__querybc=true&__showtime=true&action=perform

The error I'm getting with the command 
```
java -classpath "standalone/*;as4/*" eu.sendregning.oxalis.Main -f C:\dev\oxalis\oxalis-standalone-as4\invoice.xml -r 0151:11111111138
```
is
```
Message failed : Received code 400 for lookup. URI: http://smo.storecove.com/iso6523-actorid-upis%3A%3A0151%3A11111111138/services/%3A%3Aconnectivity%3A%3Acef%23%23connectivity%3A%3AsubmitMessage

2020-04-09 16:27:36,472 ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: No transmission is provided.
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:116)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Total time spent: 1s
Attempted to send 0 files
Failed transmissions: 1
```
My OXALIS config is
```
oxalis.keystore {
     # Relative to OXALIS_HOME
     path = peppolAP.jks
     password = ******
     key.alias = le-fa2640f4-dc88-4ca6-a72f-6118cbf08b00
     key.password = *******
 }

oxalis.sml.hostname = acc.edelivery.tech.ec.europa.eu
```

Any ideas/direction would be greatly appreciated

**Comment by klakegg** [comment]
SMPs not responding according to the SMP specification is not a bug in Oxalis.
