### ISSUE TITLE
Error 500 on sending sample invoice to own access point

### ISSUE THREAD

**Issue by vincentpwnz00r** [difi/oxalis#472]
Hi i encountered error 500 when trying to send a sample invoice to my own access point 

ERROR [no.difi.oxalis.as2.outbound.As2MessageSender] AS2 HTTP POST expected HTTP OK, but got : 500 from http://localhost:8080/oxalis/as2
ERROR [eu.sendregning.oxalis.Main] Execution failed: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
`java.util.concurrent.ExecutionException: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at eu.sendregning.oxalis.Main.main(Main.java:225)
Caused by: no.difi.oxalis.api.lang.OxalisTransmissionException: Request failed with rc=500, contents received (16 characters): INTERNAL ERROR!!
        at no.difi.oxalis.as2.outbound.As2MessageSender.handleFailedRequest(As2MessageSender.java:349)
        at no.difi.oxalis.as2.outbound.As2MessageSender.handleResponse(As2MessageSender.java:276)
        at no.difi.oxalis.as2.outbound.As2MessageSender.sendHttpRequest(As2MessageSender.java:245)
        at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:154)
        at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:149)
        at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:93)
        at eu.sendregning.oxalis.TransmissionTask.performTransmission(TransmissionTask.java:166)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:94)
        at eu.sendregning.oxalis.TransmissionTask.call(TransmissionTask.java:48)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

however when i curl http://localhost:8080/oxalis/as2
it returns: Hello AS2 world

What could had gone wrong with my implementation?

**Comment by vincentpwnz00r** [comment]
This was caused by a tomcat initialisation issue and have since been resolved
